"""Brace expansion implementation for psh.

Implements bash-style brace expansion on the token stream (see
``TokenBraceExpander``). ``BraceExpander`` provides the per-word expansion
algorithm; ``TokenBraceExpander`` applies it across tokens after tokenization.
Supports:
- List expansion: {a,b,c} → a b c
- Numeric sequences: {1..10} → 1 2 3 4 5 6 7 8 9 10
- Character sequences: {a..z} → a b c ... z
- Sequences with increment: {1..10..2} → 1 3 5 7 9
- Zero-padded sequences: {01..10} → 01 02 03 04 05 06 07 08 09 10
- Nested expansions: {{1..3},{a..c}} → 1 2 3 a b c
- Preamble/postscript: file{1..3}.txt → file1.txt file2.txt file3.txt
"""

import copy
import re
from typing import List, Optional, Tuple

from .core.exceptions import PshError


class BraceExpansionError(PshError):
    """Raised when brace expansion encounters an error."""
    pass


class BraceExpander:
    """Per-word brace expansion algorithm (lists, sequences, nesting).

    Used by ``TokenBraceExpander`` to expand individual words; not invoked on
    raw command lines.
    """

    # Maximum number of items that can be generated by expansion
    MAX_EXPANSION_ITEMS = 10000

    def _expand_braces(self, text: str) -> List[str]:
        """Expand all brace expressions in text, returning list of results.

        This handles nested braces by repeatedly expanding until no more
        brace expressions are found.
        """
        # First check if braces are balanced
        if not self._are_braces_balanced(text):
            # Don't expand if braces are unbalanced
            return [text]

        results = [text]

        # Keep expanding until no more brace expressions found
        while True:
            new_results = []
            expanded_any = False

            for item in results:
                expanded = self._expand_one_brace(item)
                if len(expanded) > 1 or (expanded and expanded[0] != item):
                    expanded_any = True
                new_results.extend(expanded)

            results = new_results

            # Check expansion limit
            if len(results) > self.MAX_EXPANSION_ITEMS:
                raise BraceExpansionError(
                    f"Brace expansion would create {len(results)} items "
                    f"(limit: {self.MAX_EXPANSION_ITEMS})"
                )

            if not expanded_any:
                break

        return results

    def _are_braces_balanced(self, text: str) -> bool:
        """Check if braces are properly balanced in text."""
        depth = 0
        escaped = False

        for char in text:
            if escaped:
                escaped = False
                continue

            if char == '\\':
                escaped = True
                continue

            if char == '{':
                depth += 1
            elif char == '}':
                depth -= 1
                if depth < 0:
                    # More closing than opening
                    return False

        # Check if all braces were closed
        return depth == 0

    def _expand_one_brace(self, text: str) -> List[str]:
        """Expand the first brace expression found in text.

        Returns a list with the expanded results, or [text] if no
        valid brace expression is found.
        """
        # Find a complete brace expression
        brace_match = self._find_brace_expression(text)
        if not brace_match:
            return [text]

        start, end, brace_content = brace_match
        prefix = text[:start]
        suffix = text[end:]

        # Special handling for shell metacharacters in suffix
        # If the suffix starts with certain metacharacters that should not be
        # attached to each expansion, we need to handle them differently
        attach_suffix = suffix
        detached_suffix = ""

        # Check if suffix starts with a shell metacharacter that should be detached
        # from the brace expansion (applies to both sequences and lists)
        if suffix:
            # Check for multi-character operators first
            multi_char_operators = ['&&', '||', '>>', '<<']
            detach_operator = None

            for op in multi_char_operators:
                if suffix.startswith(op):
                    detach_operator = op
                    break

            # Check for single-character operators
            if not detach_operator and suffix[0] in ';|&)]}':
                detach_operator = suffix[0]

            if detach_operator:
                # For brace expansions followed by shell operators, detach them
                attach_suffix = ""
                detached_suffix = suffix

        # Determine brace type and expand
        # Check if it's a list (has comma at top level) or pure sequence
        if self._has_top_level_comma(brace_content):
            # List expansion (may contain nested sequences)
            expanded = self._expand_list(brace_content)
        elif '..' in brace_content:
            # Pure sequence expansion
            expanded = self._expand_sequence(brace_content)
            if expanded is None:
                # Invalid sequence, return unexpanded
                return [text]
        else:
            # No comma and no .., not a valid brace expression
            return [text]

        # Combine with prefix/suffix
        if detached_suffix:
            # Join expanded items with spaces, then add the detached suffix
            return [prefix + ' '.join(expanded) + detached_suffix]
        else:
            # Normal case - attach suffix to each item
            return [prefix + item + attach_suffix for item in expanded]

    def _expand_list(self, content: str) -> List[str]:
        """Expand comma-separated list like a,b,c.

        Handles nested braces by careful parsing of the content.
        """
        # Parse the content respecting nested braces
        items = []
        current = []
        depth = 0
        escaped = False

        for i, char in enumerate(content):
            if escaped:
                current.append(char)
                escaped = False
                continue

            if char == '\\':
                escaped = True
                current.append(char)
            elif char == '{':
                depth += 1
                current.append(char)
            elif char == '}':
                depth -= 1
                current.append(char)
            elif char == ',' and depth == 0:
                # Found a separator at top level
                items.append(''.join(current))
                current = []
            else:
                current.append(char)

        # Don't forget the last item
        items.append(''.join(current))

        # Recursively expand any nested braces in items
        expanded_items = []
        for item in items:
            # Empty items should remain empty
            if item == '':
                expanded_items.append('')
            else:
                # Check if this item contains a sequence
                if '..' in item and '{' in item and '}' in item:
                    # This might be a nested sequence like {1..3}
                    expanded = self._expand_braces(item)
                    expanded_items.extend(expanded)
                else:
                    # Regular item or already expanded
                    expanded_items.extend(self._expand_braces(item))

        return expanded_items

    def _find_brace_expression(self, text: str) -> Optional[Tuple[int, int, str]]:
        """Find the first valid brace expression in text.

        Returns:
            Tuple of (start_index, end_index, content) or None if not found.
            end_index is one past the closing brace.
        """
        depth = 0
        start = -1
        escaped = False

        for i, char in enumerate(text):
            if escaped:
                escaped = False
                continue

            if char == '\\':
                escaped = True
                continue

            if char == '{':
                if depth == 0:
                    # Check if this is a variable expansion ${...}
                    if i > 0 and text[i-1] == '$':
                        # This is a variable expansion, not a brace expansion
                        # Skip to the closing brace
                        j = i + 1
                        brace_depth = 1
                        while j < len(text) and brace_depth > 0:
                            if text[j] == '{':
                                brace_depth += 1
                            elif text[j] == '}':
                                brace_depth -= 1
                            j += 1
                        i = j - 1  # Will be incremented by the loop
                        continue
                    start = i
                depth += 1
            elif char == '}':
                depth -= 1
                if depth == 0 and start >= 0:
                    content = text[start+1:i]
                    # Validate it's a real brace expression
                    if self._is_valid_brace_content(content):
                        return (start, i+1, content)
                    # Not valid, reset and continue looking
                    start = -1
                elif depth < 0:
                    # More closing than opening braces - this is invalid
                    # Don't try to expand anything
                    return None

        # If we have unclosed braces, don't expand
        if depth > 0:
            return None

        return None

    def _is_valid_brace_content(self, content: str) -> bool:
        """Check if content represents a valid brace expression.

        Valid expressions have either:
        - A comma at the top level (not inside nested braces)
        - A '..' sequence (for range expansion)

        Note: brace expansion is purely textual and runs *before* parameter,
        command, and arithmetic expansion, so a list whose items contain
        $var / $(...) / $((...)) must still expand (bash: `echo {$a,$b}` ->
        the two words `$a` `$b`, expanded afterwards). Ranges with $-endpoints
        are not expandable (their bounds aren't integers/chars at brace time);
        those are left literal by _expand_sequence returning None.
        """
        if not content:
            return False

        # Check for sequence (Phase 2 - recognize but don't expand yet)
        if '..' in content:
            # Additional validation for sequences
            parts = content.split('..')
            if len(parts) < 2 or len(parts) > 3:
                return False
            # Start and end must not be empty
            start = parts[0]
            end = parts[1]
            if not start or not end:
                return False
            return True

        # Check for list (must have comma not inside nested braces)
        depth = 0
        escaped = False
        has_comma = False

        for char in content:
            if escaped:
                escaped = False
                continue

            if char == '\\':
                escaped = True
            elif char == '{':
                depth += 1
            elif char == '}':
                depth -= 1
            elif char == ',' and depth == 0:
                has_comma = True

        # Also check that we don't have spaces around commas
        # "{a, b, c}" should not expand
        if has_comma and not self._has_spaces_around_commas(content):
            return True

        return False

    def _has_spaces_around_commas(self, content: str) -> bool:
        """Check if content has spaces around any top-level commas."""
        depth = 0
        escaped = False

        for i, char in enumerate(content):
            if escaped:
                escaped = False
                continue

            if char == '\\':
                escaped = True
            elif char == '{':
                depth += 1
            elif char == '}':
                depth -= 1
            elif char == ',' and depth == 0:
                # Check for spaces around this comma
                if (i > 0 and content[i-1] == ' ') or \
                   (i < len(content)-1 and content[i+1] == ' '):
                    return True

        return False

    def _has_top_level_comma(self, content: str) -> bool:
        """Check if content has a comma at top level (not inside nested braces)."""
        depth = 0
        escaped = False

        for char in content:
            if escaped:
                escaped = False
                continue

            if char == '\\':
                escaped = True
            elif char == '{':
                depth += 1
            elif char == '}':
                depth -= 1
            elif char == ',' and depth == 0:
                return True

        return False

    def _expand_sequence(self, content: str) -> Optional[List[str]]:
        """Expand sequence like 1..10 or a..z.

        Returns None if the sequence is invalid.
        """
        # Parse the sequence
        parts = content.split('..')
        if len(parts) < 2 or len(parts) > 3:
            return None

        start = parts[0]
        end = parts[1]
        increment = parts[2] if len(parts) == 3 else '1'

        # Validate that start and end are not empty (invalid sequences like {1..} or {..5})
        if not start or not end:
            return None

        # Try numeric sequence first
        numeric_result = self._try_numeric_sequence(start, end, increment)
        if numeric_result is not None:
            return numeric_result

        # Try character sequence
        char_result = self._try_char_sequence(start, end, increment)
        if char_result is not None:
            return char_result

        # Invalid sequence
        return None

    def _try_numeric_sequence(self, start: str, end: str, increment: str) -> Optional[List[str]]:
        """Try to expand as numeric sequence.

        Returns None if not valid numeric sequence.
        """
        try:
            # Parse numbers
            start_num = int(start)
            end_num = int(end)
            inc_num = int(increment)

            # Handle increment of 0
            if inc_num == 0:
                inc_num = 1

            # Determine direction
            if start_num <= end_num:
                inc_num = abs(inc_num)
            else:
                inc_num = -abs(inc_num)

            # Determine padding
            padding = self._determine_numeric_padding(start, end)

            # Generate sequence
            result = []
            current = start_num
            while (inc_num > 0 and current <= end_num) or (inc_num < 0 and current >= end_num):
                if padding < 0:
                    # Special case: -3..03 style
                    # Negative numbers don't get padded, positive do
                    if current < 0:
                        result.append(str(current))
                    else:
                        result.append(str(current).zfill(-padding))
                elif padding > 0:
                    # Handle padding based on whether range crosses zero
                    if start_num < 0 and end_num >= 0:
                        # Range crosses zero - bash uses special padding
                        # Negative numbers get one less padding digit than positive
                        if current < 0:
                            result.append('-' + str(abs(current)).zfill(padding))
                        else:
                            # Zero and positive get extra digit
                            result.append(str(current).zfill(padding + 1))
                    else:
                        # Normal padding
                        if current < 0:
                            result.append('-' + str(abs(current)).zfill(padding))
                        else:
                            result.append(str(current).zfill(padding))
                else:
                    result.append(str(current))
                current += inc_num

            return result

        except ValueError:
            return None

    def _try_char_sequence(self, start: str, end: str, increment: str) -> Optional[List[str]]:
        """Try to expand as character sequence.

        Returns None if not valid character sequence.
        """
        # Must be single characters
        if len(start) != 1 or len(end) != 1:
            return None

        # Must be ASCII letters
        start_ord = ord(start)
        end_ord = ord(end)

        # For character sequences, we accept any ASCII character between bounds
        # but start and end must be letters for the sequence to be valid
        if not ((start.isalpha() and end.isalpha()) or
                (start.isdigit() and end.isdigit())):
            # Special case: allow cross-case sequences like A..z
            if not (start.isalpha() and end.isalpha()):
                return None

        try:
            inc_num = int(increment)
            if inc_num == 0:
                inc_num = 1
        except ValueError:
            return None

        # Determine direction
        if start_ord <= end_ord:
            inc_num = abs(inc_num)
        else:
            inc_num = -abs(inc_num)

        # Generate sequence
        result = []
        current = start_ord
        while (inc_num > 0 and current <= end_ord) or (inc_num < 0 and current >= end_ord):
            result.append(chr(current))
            current += inc_num

        return result

    def _determine_numeric_padding(self, start: str, end: str) -> int:
        """Determine zero-padding width for numeric sequence.

        Returns 0 if no padding needed.
        """
        # Remove sign for padding calculation
        start_digits = start.lstrip('-+')
        end_digits = end.lstrip('-+')

        # Check if either has leading zeros
        has_start_padding = len(start_digits) > 1 and start_digits.startswith('0')
        has_end_padding = len(end_digits) > 1 and end_digits.startswith('0')

        if not (has_start_padding or has_end_padding):
            return 0

        # For single digit negative padded number like -3 with end 03,
        # we don't pad the negative numbers
        start_val = int(start)

        # If start is negative without padding and end has padding
        if start_val < 0 and not has_start_padding and has_end_padding:
            # Return 0 to indicate special handling
            return -len(end_digits)  # Negative indicates special case

        # Padding is the max length
        return max(len(start_digits), len(end_digits))

    def _contains_expandable_dollar(self, content: str) -> bool:
        """Check if content contains actual variable/command substitution patterns.

        Returns True for patterns like:
        - $var or ${var} (variable expansion)
        - $(cmd) (command substitution)
        - $((expr)) (arithmetic expansion)

        Returns False for:
        - Single '$' not followed by variable name or special pattern
        - '$' at end of string
        - '$' followed by comma or other non-variable characters
        """
        i = 0
        while i < len(content):
            if content[i] == '$':
                if i + 1 >= len(content):
                    # $ at end of string
                    i += 1
                    continue

                next_char = content[i + 1]

                # Check for ${...}, $(...), or $((...))
                if next_char in '{(':
                    return True

                # Check for $var pattern (letter or underscore starts variable)
                if next_char.isalpha() or next_char == '_':
                    return True

                # Check for special variables like $1, $@, $*, etc.
                # But not if followed by comma (as in {$,#,@})
                if next_char == ',':
                    # $ followed by comma is not a variable
                    i += 1
                    continue

                if next_char.isdigit() or next_char in '@*#?-!$':
                    return True

                # Otherwise, it's just a literal $
                i += 1
            else:
                i += 1

        return False


# Words matching this are variable assignments (name=, name[idx]=, name+=).
# Brace expansion is suppressed on assignment words in command-prefix position
# (bash: `a={x,y}` stays literal, but `echo a={x,y}` expands).
_ASSIGNMENT_RE = re.compile(r'^[A-Za-z_][A-Za-z0-9_]*(\[[^\]]*\])?\+?=')


class TokenBraceExpander:
    """Brace expansion performed on a token stream (post-tokenization).

    This replaces expanding the raw command text and re-lexing the result.
    Working on tokens means:

    - characters generated by a range (e.g. the backtick in ``{Z..a}``) stay
      literal — nothing is re-lexed (fixes the re-lex crash);
    - quote context is already resolved by the lexer;
    - assignment words can be left unexpanded using command-prefix position.

    Increment 1 handles standalone, unquoted ``WORD`` tokens. Brace words that
    are part of a composite (adjacent to a quoted neighbour, e.g. ``{"[",x}``)
    are left unchanged and handled by a later increment.
    """

    def __init__(self):
        self._core = BraceExpander()

    # Token types that glue to a neighbour to form one composite word.
    def _word_like(self):
        from .token_types import TokenType
        return {
            TokenType.WORD, TokenType.STRING, TokenType.VARIABLE,
            TokenType.COMMAND_SUB, TokenType.ARITH_EXPANSION,
        }

    def _reset_types(self):
        from .token_types import TokenType
        return {
            TokenType.SEMICOLON, TokenType.NEWLINE, TokenType.AND_AND,
            TokenType.OR_OR, TokenType.PIPE, TokenType.DOUBLE_SEMICOLON,
            TokenType.SEMICOLON_AMP, TokenType.AMP_SEMICOLON,
            TokenType.AMPERSAND, TokenType.THEN, TokenType.DO, TokenType.ELSE,
            TokenType.ELIF, TokenType.FI, TokenType.DONE, TokenType.ESAC,
            TokenType.LPAREN, TokenType.RPAREN, TokenType.LBRACE,
            TokenType.RBRACE, TokenType.IF, TokenType.WHILE, TokenType.UNTIL,
        }

    def expand(self, tokens):
        if not tokens:
            return tokens

        word_like = self._word_like()
        reset_types = self._reset_types()

        out = []
        zone_active = True  # in a command-prefix (assignment-allowed) position
        n = len(tokens)
        i = 0

        while i < n:
            tok = tokens[i]
            if tok.type in word_like:
                # Gather a maximal run of adjacent word-forming tokens — these
                # together form one logical (possibly composite) word.
                j = i
                while (j + 1 < n and tokens[j + 1].type in word_like
                       and getattr(tokens[j + 1], 'adjacent_to_previous', False)):
                    j += 1
                run = tokens[i:j + 1]
                out.extend(self._expand_run(run, zone_active))
                zone_active = self._zone_after_word(run[0], zone_active)
                i = j + 1
            else:
                out.append(tok)
                zone_active = True if tok.type in reset_types else zone_active
                i += 1

        return out

    def _zone_after_word(self, first_tok, zone_active):
        from .token_types import TokenType
        # An assignment word keeps the command prefix open (a=1 b=2 cmd); any
        # other word is the command name (or an argument) and ends the prefix.
        if (first_tok.type == TokenType.WORD and zone_active
                and first_tok.value and _ASSIGNMENT_RE.match(first_tok.value)):
            return True
        return False

    def _expand_run(self, run, zone_active):
        from .token_types import TokenType
        first = run[0]
        # Suppress brace expansion on a command-prefix assignment (a={x,y}).
        if (zone_active and first.type == TokenType.WORD
                and first.value and _ASSIGNMENT_RE.match(first.value)):
            return list(run)

        if len(run) == 1:
            tok = run[0]
            if (tok.type == TokenType.WORD and tok.quote_type is None
                    and tok.value and '{' in tok.value):
                try:
                    expansions = self._core._expand_braces(tok.value)
                except BraceExpansionError:
                    expansions = [tok.value]
                if not (len(expansions) == 1 and expansions[0] == tok.value):
                    # bash drops results that expand to the empty string
                    # ({a,,b} -> a b); an empty item fused with a prefix/postfix
                    # is non-empty and survives (a{,b} -> a ab).
                    expansions = [e for e in expansions if e != '']
                    return self._make_word_tokens(tok, expansions)
            return list(run)

        # Composite run (adjacent tokens forming one word). Only unquoted braces
        # are structural. Expansion tokens ($((..)), $(..), $var) are carried
        # through as opaque units so brace *list* items that are expansions still
        # expand (bash: `{$((1)),$((2))}` -> `1 2`). The one case the token model
        # cannot reproduce is bash re-forming a variable *name* out of brace text
        # (`$x{1,2}` -> `$x1 $x2`); _expand_composite bails on that, leaving the
        # run unexpanded as before.
        composite = self._expand_composite(run)
        if composite is not None:
            return composite
        return list(run)

    def _expand_composite(self, run):
        """Expand braces across a composite run of tokens.

        Encoding (so the reused string expander only treats UNQUOTED braces and
        commas as structural):
          - unquoted WORD chars  -> kept literal (their { , } .. are structural);
          - quoted chars         -> one private-use placeholder each, preserving
                                     quote type;
          - any other token      -> one private-use placeholder for the WHOLE
            (e.g. $((..)), $(..), $var)  token (opaque; never structural).
        Placeholders are decoded afterwards to rebuild each result word. Returns
        the new token list, or None if nothing expanded / the result cannot be
        represented faithfully (see the name-fusion guard below).
        """
        from .token_types import TokenType

        # 1. Encode the run into a string of literal chars + placeholders.
        char_map = {}   # placeholder -> (char, quote_type)
        tok_map = {}    # placeholder -> whole token
        encoded = []
        next_pu = 0xE000
        for tok in run:
            if tok.type == TokenType.WORD and tok.quote_type is None:
                encoded.append(tok.value or '')
            elif tok.type in (TokenType.WORD, TokenType.STRING):
                qt = tok.quote_type
                for ch in (tok.value or ''):
                    pu = chr(next_pu); next_pu += 1
                    char_map[pu] = (ch, qt)
                    encoded.append(pu)
            else:
                pu = chr(next_pu); next_pu += 1
                tok_map[pu] = tok
                encoded.append(pu)
        encoded_str = ''.join(encoded)

        # 2. Expand using the shared core (sees only unquoted braces/commas).
        try:
            results = self._core._expand_braces(encoded_str)
        except BraceExpansionError:
            return None
        if len(results) == 1 and results[0] == encoded_str:
            return None  # nothing structural to expand

        # 3. Name-fusion guard: bash would re-form `$x` + adjacent unquoted name
        #    char into the parameter `$x<char>`; the token model keeps `$x` a
        #    separate VARIABLE token, so it cannot reproduce that. If any result
        #    places a VARIABLE token immediately before an unquoted name char,
        #    leave the whole run unexpanded (preserving prior behaviour).
        for result in results:
            for k, c in enumerate(result):
                tok = tok_map.get(c)
                if tok is not None and tok.type == TokenType.VARIABLE:
                    nxt = result[k + 1] if k + 1 < len(result) else ''
                    if nxt and nxt not in char_map and nxt not in tok_map \
                            and (nxt.isalnum() or nxt == '_'):
                        return None

        # 4. Decode each result and emit tokens.
        out = []
        first_word = True
        for result in results:
            if not result:
                continue  # bash drops fully-empty results
            leading_adjacent = (
                getattr(run[0], 'adjacent_to_previous', False)
                if first_word else False
            )
            out.extend(self._emit_word(result, char_map, tok_map, run[0],
                                       leading_adjacent))
            first_word = False
        return out

    def _emit_word(self, result, char_map, tok_map, template, leading_adjacent):
        """Turn one expanded result (literal chars + placeholders) into tokens.

        Consecutive characters of the same quote type form one token (WORD when
        unquoted, STRING when quoted); opaque-token placeholders are emitted as
        copies of their original token. All tokens of one result word are marked
        adjacent so the parser merges them back into a single composite word.
        """
        from .lexer.token_parts import TokenPart
        from .token_types import TokenType

        # Build segments: ('chars', text, quote_type) or ('tok', token).
        segments = []
        for c in result:
            if c in tok_map:
                segments.append(('tok', tok_map[c]))
                continue
            ch, qt = char_map.get(c, (c, None))
            if segments and segments[-1][0] == 'chars' and segments[-1][2] == qt:
                segments[-1] = ('chars', segments[-1][1] + ch, qt)
            else:
                segments.append(('chars', ch, qt))

        toks = []
        for idx, seg in enumerate(segments):
            adjacent = leading_adjacent if idx == 0 else True
            if seg[0] == 'tok':
                tok = copy.copy(seg[1])
                tok.adjacent_to_previous = adjacent
                toks.append(tok)
                continue
            _, text, qt = seg
            tok = copy.copy(template)
            tok.value = text
            tok.adjacent_to_previous = adjacent
            if qt is None:
                tok.type = TokenType.WORD
                tok.quote_type = None
                tok.parts = []
            else:
                tok.type = TokenType.STRING
                tok.quote_type = qt
                tok.parts = [TokenPart(value=text, quote_type=qt)]
            toks.append(tok)
        return toks

    @staticmethod
    def _make_word_tokens(orig, values):
        toks = []
        for idx, value in enumerate(values):
            tok = copy.copy(orig)
            tok.value = value
            # The lexer's per-part metadata no longer matches the new value;
            # unquoted WORD tokens are rebuilt from `.value` downstream.
            tok.parts = []
            if idx > 0:
                # Expanded items are separate words, not a composite run.
                tok.adjacent_to_previous = False
            toks.append(tok)
        return toks
