"""``read -N`` must honor ``-t`` (slot 4B.2, the A5 rider).

``_read_exact`` called ``read_limited(delimiter=None, max_chars=count)`` with no
``deadline=``, while lowercase ``-n`` got one through ``_read_with_timeout``. So
``read -t 1 -N 3`` ignored the timeout and blocked until EOF — and with no EOF
at all it blocked forever.

**How these cells avoid the traps this slot already hit:**

* *No concurrent producer at all.* ``exec 3<>fifo`` opens the FIFO read-WRITE,
  so a writer always exists and EOF NEVER arrives; the deadline is then the only
  clock in the cell. "Input that arrives too late" is expressed by writing it
  AFTER the read has returned, in the same shell, rather than by a backgrounded
  ``sleep`` — by construction instead of by wall-clock luck. Only the
  EOF-after-the-deadline cells use a timed producer, at 2x the deadline, and
  they are a pipeline the shell fully waits on, so nothing outlives them.
* *Per-arm FIFOs and payload files.* The two shells never share one — see
  ``_fifo``.
* *Bytes are never generated by the shell under test.* ``printf '\\303'`` emits
  one byte in bash and two in psh, so a multibyte stimulus written in shell
  would compare two different experiments. The payload is written to a file by
  the TEST and injected with ``cat`` (external, identical for both shells).
* *Values are compared as raw bytes* through ``od``, never ``printf %q``, whose
  rendering of a non-UTF-8 byte differs per shell.
* *Bounded kill.* Every case goes through ``shell_oracle``, whose watchdog
  SIGKILLs the whole process group and sweeps descendants; a psh that ignores
  the deadline surfaces as a non-comparable Timeout, never as a hung suite.

**Declared residue.** Two families stay DIFFER from bash after this fix, by
integrator ruling, and are pinned here as labelled psh-CONTRACT cells that
assert psh's value AND that bash's differs — so they flip LOUDLY when the
owning slot rules:

* **D-4B.2-s1 (NEW-1, RULED a permanent psh contract in 4B.4):** on timeout bash ASSIGNS the
  stranded partial multibyte bytes; psh holds them on the cursor for the next
  read. rc agrees (142); only the value differs.
* **D-4B.2-s2 (NEW-2, out of charter):** bash counts POST-escape characters for
  ``-N``, psh counts raw characters. Visible without any ``-t`` at all, so this
  fix neither causes nor cures it. Measured here to diverge in the EXIT STATUS
  as well as the value — correcting this slot's own pre-registration, which had
  recorded it as an rc-parity cell.
"""
import os

import pytest
from shell_oracle import is_comparable, run_bash, run_psh

pytestmark = pytest.mark.serial  # real deadlines: parallel siblings must not
                                 # starve the clock

TIMEOUT = 1.0        # the -t deadline every cell uses
LATE = 2.0           # a late writer / late EOF: 2x the deadline
KILL_AFTER = 8.0     # the runner's watchdog: 8x the deadline

# Report rc and the variable's RAW BYTES via external od.
_REPORT = (r"""rc=$?; printf 'rc=%s bytes=' "$rc"; """
           r"""printf '%s' "$x" | od -An -tx1 | tr -d ' \n'; printf '\n'""")


def _payload(tmp_path, arm: str, data: bytes, name="payload") -> str:
    p = tmp_path / f"{arm}.{name}.bin"
    p.write_bytes(data)
    return str(p)


def _fifo(tmp_path, arm: str) -> str:
    """A FIFO private to ONE arm.

    The two arms must never share one. An earlier version of this file reused a
    single FIFO for both, and a cell whose writer outlived its shell delivered
    that writer's bytes into the OTHER arm's run — a cross-arm race that made
    bash look like it had ignored its own deadline. Per-arm FIFOs (and per-arm
    payload files) keep each cell's two runs genuinely independent.
    """
    f = str(tmp_path / f"{arm}.fifo")
    os.mkfifo(f)
    return f


def _no_eof_script(tmp_path, arm: str, opts: str, data: bytes = b"") -> str:
    """A source that NEVER reaches EOF: fd 3 is read-write on a FIFO."""
    fifo = _fifo(tmp_path, arm)
    feed = f"cat {_payload(tmp_path, arm, data)} >&3; " if data else ""
    return f"exec 3<>{fifo}; {feed}read {opts} x <&3; {_REPORT}"


def _write_after_read_script(tmp_path, arm: str, opts: str, before: bytes,
                             after: bytes) -> str:
    """Bytes that arrive strictly AFTER the read returned.

    ``after`` is written by the SAME shell once ``read`` has finished, so it
    provably could not have been consumed — no background writer, no sleep, no
    race. (A backgrounded ``sleep``-then-write would test the same property by
    wall-clock luck; this tests it by construction.)
    """
    fifo = _fifo(tmp_path, arm)
    feed = f"cat {_payload(tmp_path, arm, before, 'before')} >&3; " if before else ""
    later = _payload(tmp_path, arm, after, "after")
    return (f"exec 3<>{fifo}; {feed}read {opts} x <&3; rc=$?; "
            f"cat {later} >&3; "
            f"""printf 'rc=%s bytes=' "$rc"; """
            f"""printf '%s' "$x" | od -An -tx1 | tr -d ' \\n'; printf '\\n'""")


def _eof_script(tmp_path, arm: str, opts: str, data: bytes, *,
                hold: float = 0.0) -> str:
    """A real EOF, optionally held open past the deadline first."""
    held = f"; sleep {hold}" if hold else ""
    # NB the `;` before the closing brace: a brace group needs a separator
    # there, and BOTH shells reject the script identically without it — which
    # `is_comparable` happily calls comparable, so the breakage surfaces only as
    # missing output. Keep the separator.
    return (f"{{ cat {_payload(tmp_path, arm, data)}{held}; }} | "
            f"{{ read {opts} x; {_REPORT}; }}")


def _both(build, tmp_path):
    """Run one cell under psh and bash; return (psh_line, bash_line).

    ``build(arm)`` is called once PER ARM so each shell gets its own FIFO and
    payload files — see ``_fifo`` for why sharing them is unsafe.
    """
    kwargs = dict(cwd=str(tmp_path), timeout=KILL_AFTER,
                  env={"LC_ALL": "en_US.UTF-8", "LANG": "en_US.UTF-8"})
    # Arm tags name the scratch files, so they must not be the word "bash":
    # the oracle-resolution guard reads a bare 'bash' call argument as a
    # hardcoded oracle binary, and it is right to — the tag is renamed rather
    # than the guard allowlisted.
    psh = run_psh(["-c", build("psh")], **kwargs)
    bash = run_bash(["-c", build("oracle")], **kwargs)
    assert is_comparable(bash), f"bash oracle unusable: {bash}"
    assert is_comparable(psh), (
        f"psh did not complete within {KILL_AFTER}s — the deadline was ignored "
        f"and the read blocked: {psh}")
    return _line(psh), _line(bash)


def _line(result) -> str:
    lines = [ln for ln in result.stdout.splitlines() if ln.startswith("rc=")]
    assert lines, f"no report line in {result.stdout!r}"
    return lines[-1]



def _assert_parity(build, tmp_path):
    psh, bash = _both(build, tmp_path)
    assert psh == bash, f"psh {psh!r} != bash {bash!r}"
    return psh


def _assert_psh_contract(build, tmp_path, expected_psh: str, successor: str,
                         *, rc_matches: bool):
    """A labelled psh-CONTRACT cell: a DECLARED divergence from bash.

    Asserts psh's exact observable AND that bash's differs, so the cell fails
    loudly if either side moves — including when the successor row is finally
    ruled and psh is meant to converge. ``rc_matches`` records whether the
    divergence is value-only (the exit status still agrees) or reaches the exit
    status too; getting that wrong is itself a finding, so it is asserted, not
    assumed.
    """
    psh, bash = _both(build, tmp_path)
    assert psh == expected_psh, (
        f"psh observable moved: {psh!r} != {expected_psh!r} ({successor})")
    assert psh != bash, (
        f"{successor}: this divergence from bash is DECLARED — psh {psh!r} now "
        f"equals bash {bash!r}. If the successor row was ruled, update this pin "
        f"and the doc it cites.")
    psh_rc, bash_rc = psh.split()[0], bash.split()[0]
    if rc_matches:
        assert psh_rc == bash_rc, (
            f"{successor} was recorded as a VALUE-ONLY divergence but the exit "
            f"status now differs too: psh {psh_rc} vs bash {bash_rc}")
    else:
        assert psh_rc != bash_rc, (
            f"{successor} was recorded as reaching the EXIT STATUS but the "
            f"statuses now agree ({psh_rc}) — reclassify the row")


# --------------------------------------------------------------------------
# RED-on-base: the rider itself. After the fix psh matches bash on rc AND value.
# --------------------------------------------------------------------------

class TestRiderParityFull:
    def test_no_input_and_no_eof_times_out(self, tmp_path):
        line = _assert_parity(
            lambda arm: _no_eof_script(tmp_path, arm, f"-t {TIMEOUT} -N 3"),
            tmp_path)
        assert line == "rc=142 bytes="

    def test_partial_input_and_no_eof_assigns_the_partial(self, tmp_path):
        line = _assert_parity(
            lambda arm: _no_eof_script(tmp_path, arm, f"-t {TIMEOUT} -N 3",
                                       b"ab"),
            tmp_path)
        assert line == "rc=142 bytes=6162"

    def test_input_arriving_after_the_read_is_not_consumed(self, tmp_path):
        line = _assert_parity(
            lambda arm: _write_after_read_script(
                tmp_path, arm, f"-t {TIMEOUT} -N 3", b"", b"abc"),
            tmp_path)
        assert line == "rc=142 bytes="

    def test_deadline_wins_over_a_later_eof(self, tmp_path):
        # The partial arrives at once, EOF only at 2x the deadline: bash reports
        # the TIMEOUT (142), not the EOF (1).
        line = _assert_parity(
            lambda arm: _eof_script(tmp_path, arm, f"-t {TIMEOUT} -N 3", b"ab",
                                    hold=LATE),
            tmp_path)
        assert line == "rc=142 bytes=6162"


class TestRiderRcParityWithDeclaredNew1Residue:
    """rc must match bash; the stranded partial byte is D-4B.2-s1, ruled psh's permanent
    contract in slot 4B.4 and documented in the user guide.

    A VALUE-ONLY divergence: bash assigns the stranded partial multibyte bytes
    to the timed-out read, psh holds them on the cursor for the next read.
    """

    S1 = "D-4B.2-s1 (timeout-partial hold-and-resume: psh's RULED contract, 4B.4)"

    def test_two_byte_char_split_by_the_deadline(self, tmp_path):
        _assert_psh_contract(
            lambda arm: _no_eof_script(tmp_path, arm, f"-t {TIMEOUT} -N 2",
                                       b"a\xc3"),
            tmp_path, "rc=142 bytes=61", self.S1, rc_matches=True)

    def test_three_byte_char_split_by_the_deadline(self, tmp_path):
        _assert_psh_contract(
            lambda arm: _no_eof_script(tmp_path, arm, f"-t {TIMEOUT} -N 2",
                                       b"a\xe2\x82"),
            tmp_path, "rc=142 bytes=61", self.S1, rc_matches=True)

    def test_continuation_byte_arrives_after_the_read(self, tmp_path):
        _assert_psh_contract(
            lambda arm: _write_after_read_script(
                tmp_path, arm, f"-t {TIMEOUT} -N 2", b"a\xc3", b"\xa9"),
            tmp_path, "rc=142 bytes=61", self.S1, rc_matches=True)


# --------------------------------------------------------------------------
# CHARACTERIZATION (green on base AND at the tip): pre-existing divergences this
# slot neither causes nor cures. Kept apart from the red-on-base classes above
# so the per-class split stays an integrity check — a green cell filed among
# reds lets two opposite registration errors cancel into a clean-looking total.
# --------------------------------------------------------------------------

class TestNew2CountModelDivergesInStatusTooCharacterization:
    """CHARACTERIZATION, GREEN ON BASE. The ``-N`` count model diverges from
    bash in the EXIT STATUS, not only the value — a correction to this slot's
    own pre-registration (erratum E-1).

    D-4B.2-s2: bash counts POST-escape characters for ``-N``, psh counts raw
    characters. Over ``a\\b`` with ``-N 3`` bash still needs a third post-escape
    character and so times out (142); psh has already consumed its three raw
    characters and succeeds (0). The pre-registration recorded this as an
    rc-parity cell with a value-only residue AND as red-on-base; both halves
    were wrong, and the cell is pinned here in its measured shape. Visible with
    no ``-t`` at all (see
    ``TestRiderMustHoldControls.test_raw_mode_keeps_the_backslash`` and the
    isolation cells in the Phase A instrument), so the rider fix neither causes
    nor cures it — which is exactly why it belongs in the characterization
    section and not among the red-on-base classes.
    """

    def test_backslash_under_deadline_diverges_in_rc_and_value(self, tmp_path):
        _assert_psh_contract(
            lambda arm: _no_eof_script(tmp_path, arm, f"-t {TIMEOUT} -N 3",
                                       b"a\\b"),
            tmp_path, "rc=0 bytes=6162",
            "D-4B.2-s2 (-N counts raw chars in psh, post-escape in bash)",
            rc_matches=False)


# --------------------------------------------------------------------------
# Must-hold: these already match bash at base and must not move.
# --------------------------------------------------------------------------

class TestRiderMustHoldControls:
    def test_count_satisfied_before_the_deadline(self, tmp_path):
        assert _assert_parity(
            lambda arm: _no_eof_script(tmp_path, arm, f"-t {TIMEOUT} -N 3",
                                       b"abc"),
            tmp_path) == "rc=0 bytes=616263"

    def test_eof_before_the_count_without_t(self, tmp_path):
        assert _assert_parity(
            lambda arm: _eof_script(tmp_path, arm, "-N 3", b"ab"),
            tmp_path) == "rc=1 bytes=6162"

    def test_eof_before_the_count_with_t(self, tmp_path):
        assert _assert_parity(
            lambda arm: _eof_script(tmp_path, arm, f"-t {TIMEOUT} -N 3", b"ab"),
            tmp_path) == "rc=1 bytes=6162"

    def test_zero_count_with_t_returns_at_once(self, tmp_path):
        assert _assert_parity(
            lambda arm: _no_eof_script(tmp_path, arm, f"-t {TIMEOUT} -N 0"),
            tmp_path) == "rc=0 bytes="

    def test_poll_with_data_ready_assigns_nothing(self, tmp_path):
        # `-t 0` is a non-consuming poll and precedes the -N branch: readable
        # means rc 0 with the variable untouched.
        assert _assert_parity(
            lambda arm: _no_eof_script(tmp_path, arm, "-t 0 -N 3", b"abc"),
            tmp_path) == "rc=0 bytes="

    def test_poll_with_no_data_reports_would_block(self, tmp_path):
        assert _assert_parity(
            lambda arm: _no_eof_script(tmp_path, arm, "-t 0 -N 3"),
            tmp_path) == "rc=1 bytes="

    def test_delimiter_is_ignored_under_exact_count(self, tmp_path):
        assert _assert_parity(
            lambda arm: _no_eof_script(tmp_path, arm, f"-t {TIMEOUT} -d : -N 3",
                                       b"a:bc"),
            tmp_path) == "rc=0 bytes=613a62"

    def test_raw_mode_keeps_the_backslash(self, tmp_path):
        assert _assert_parity(
            lambda arm: _eof_script(tmp_path, arm, "-r -N 3", b"a\\b"),
            tmp_path) == "rc=0 bytes=615c62"

    def test_multibyte_completed_before_the_deadline(self, tmp_path):
        assert _assert_parity(
            lambda arm: _no_eof_script(tmp_path, arm, f"-t {TIMEOUT} -N 2",
                                       b"a\xc3\xa9"),
            tmp_path) == "rc=0 bytes=61c3a9"

    def test_multibyte_truncated_at_eof_without_t(self, tmp_path):
        assert _assert_parity(
            lambda arm: _eof_script(tmp_path, arm, "-N 2", b"a\xc3"),
            tmp_path) == "rc=0 bytes=61c3"


class TestLowercaseNAndPlainTReference:
    """The ``-n`` / plain ``-t`` shapes the rider fix is modelled on.

    These are the must-hold reference: the deadline plumbing already existed on
    these paths and the fix must not disturb it. The last two are psh-CONTRACT
    cells for the same D-4B.2-s1 residue as the ``-N`` family.
    """

    S1 = "D-4B.2-s1 (timeout-partial hold-and-resume: psh's RULED contract, 4B.4)"

    def test_n_no_input_times_out(self, tmp_path):
        assert _assert_parity(
            lambda arm: _no_eof_script(tmp_path, arm, f"-t {TIMEOUT} -n 3"),
            tmp_path) == "rc=142 bytes="

    def test_n_partial_input_assigns_the_partial(self, tmp_path):
        assert _assert_parity(
            lambda arm: _no_eof_script(tmp_path, arm, f"-t {TIMEOUT} -n 3",
                                       b"ab"),
            tmp_path) == "rc=142 bytes=6162"

    def test_n_count_satisfied(self, tmp_path):
        assert _assert_parity(
            lambda arm: _no_eof_script(tmp_path, arm, f"-t {TIMEOUT} -n 3",
                                       b"abc"),
            tmp_path) == "rc=0 bytes=616263"

    def test_n_eof_before_the_count(self, tmp_path):
        assert _assert_parity(
            lambda arm: _eof_script(tmp_path, arm, f"-t {TIMEOUT} -n 3", b"ab"),
            tmp_path) == "rc=1 bytes=6162"

    def test_n_zero_count(self, tmp_path):
        assert _assert_parity(
            lambda arm: _no_eof_script(tmp_path, arm, f"-t {TIMEOUT} -n 0"),
            tmp_path) == "rc=0 bytes="

    def test_n_poll_ready(self, tmp_path):
        assert _assert_parity(
            lambda arm: _no_eof_script(tmp_path, arm, "-t 0 -n 3", b"abc"),
            tmp_path) == "rc=0 bytes="

    def test_n_poll_not_ready(self, tmp_path):
        assert _assert_parity(
            lambda arm: _no_eof_script(tmp_path, arm, "-t 0 -n 3"),
            tmp_path) == "rc=1 bytes="

    def test_plain_t_no_input(self, tmp_path):
        assert _assert_parity(
            lambda arm: _no_eof_script(tmp_path, arm, f"-t {TIMEOUT}"),
            tmp_path) == "rc=142 bytes="

    def test_plain_t_partial_line(self, tmp_path):
        assert _assert_parity(
            lambda arm: _no_eof_script(tmp_path, arm, f"-t {TIMEOUT}", b"ab"),
            tmp_path) == "rc=142 bytes=6162"

    def test_n_multibyte_split_is_psh_contract(self, tmp_path):
        _assert_psh_contract(
            lambda arm: _no_eof_script(tmp_path, arm, f"-t {TIMEOUT} -n 2",
                                       b"a\xc3"),
            tmp_path, "rc=142 bytes=61", self.S1, rc_matches=True)

    def test_plain_t_multibyte_split_is_psh_contract(self, tmp_path):
        _assert_psh_contract(
            lambda arm: _no_eof_script(tmp_path, arm, f"-t {TIMEOUT}", b"a\xc3"),
            tmp_path, "rc=142 bytes=61", self.S1, rc_matches=True)
