"""Token-stream brace expansion for psh.

``TokenBraceExpander`` applies the textual brace-expansion algorithm
(:class:`~psh.expansion.brace_expansion.BraceExpander`) across a token
stream *after* tokenization, rather than expanding the raw command text and
re-lexing the result. Working on tokens means:

- characters generated by a range (e.g. the backtick in ``{Z..a}``) stay
  literal — nothing is re-lexed;
- quote context is already resolved by the lexer;
- assignment words can be left unexpanded using command-prefix position
  (bash: ``a={x,y}`` stays literal, but ``echo a={x,y}`` expands).

It delegates the actual per-string expansion to ``BraceExpander``; this module
only handles the token-stream concerns (run gathering, quote/opaque-token
encoding, command-prefix tracking).

This module is in mypy's checked scope; keep it clean.
"""

import copy
import re
from typing import Any, List, Tuple

from .brace_expansion import _RANGE_EMPTY, BraceExpander, BraceExpansionError

# Words matching this are variable assignments (name=, name[idx]=, name+=).
# Brace expansion is suppressed on assignment words in command-prefix position
# (bash: `a={x,y}` stays literal, but `echo a={x,y}` expands).
_ASSIGNMENT_RE = re.compile(r'^[A-Za-z_][A-Za-z0-9_]*(\[[^\]]*\])?\+?=')


class TokenBraceExpander:
    """Brace expansion performed on a token stream (post-tokenization).

    This replaces expanding the raw command text and re-lexing the result.
    Working on tokens means:

    - characters generated by a range (e.g. the backtick in ``{Z..a}``) stay
      literal — nothing is re-lexed (fixes the re-lex crash);
    - quote context is already resolved by the lexer;
    - assignment words can be left unexpanded using command-prefix position.

    Increment 1 handles standalone, unquoted ``WORD`` tokens. Brace words that
    are part of a composite (adjacent to a quoted neighbour, e.g. ``{"[",x}``)
    are left unchanged and handled by a later increment.
    """

    def __init__(self):
        self._core = BraceExpander()

    # Token types that glue to a neighbour to form one composite word.
    def _word_like(self):
        from ..lexer.token_types import TokenType
        return {
            TokenType.WORD, TokenType.STRING, TokenType.VARIABLE,
            TokenType.COMMAND_SUB, TokenType.ARITH_EXPANSION,
        }

    def _reset_types(self):
        from ..lexer.token_types import TokenType
        return {
            TokenType.SEMICOLON, TokenType.NEWLINE, TokenType.AND_AND,
            TokenType.OR_OR, TokenType.PIPE, TokenType.DOUBLE_SEMICOLON,
            TokenType.SEMICOLON_AMP, TokenType.AMP_SEMICOLON,
            TokenType.AMPERSAND, TokenType.THEN, TokenType.DO, TokenType.ELSE,
            TokenType.ELIF, TokenType.FI, TokenType.DONE, TokenType.ESAC,
            TokenType.LPAREN, TokenType.RPAREN, TokenType.LBRACE,
            TokenType.RBRACE, TokenType.IF, TokenType.WHILE, TokenType.UNTIL,
        }

    def expand(self, tokens):
        if not tokens:
            return tokens

        word_like = self._word_like()
        reset_types = self._reset_types()

        out = []
        zone_active = True  # in a command-prefix (assignment-allowed) position
        n = len(tokens)
        i = 0

        while i < n:
            tok = tokens[i]
            if tok.type in word_like:
                # Gather a maximal run of adjacent word-forming tokens — these
                # together form one logical (possibly composite) word.
                j = i
                while (j + 1 < n and tokens[j + 1].type in word_like
                       and getattr(tokens[j + 1], 'adjacent_to_previous', False)):
                    j += 1
                run = tokens[i:j + 1]
                out.extend(self._expand_run(run, zone_active))
                zone_active = self._zone_after_word(run[0], zone_active)
                i = j + 1
            else:
                out.append(tok)
                zone_active = True if tok.type in reset_types else zone_active
                i += 1

        return out

    def _zone_after_word(self, first_tok, zone_active):
        from ..lexer.token_types import TokenType
        # An assignment word keeps the command prefix open (a=1 b=2 cmd); any
        # other word is the command name (or an argument) and ends the prefix.
        if (first_tok.type == TokenType.WORD and zone_active
                and first_tok.value and _ASSIGNMENT_RE.match(first_tok.value)):
            return True
        return False

    def _expand_run(self, run, zone_active):
        from ..lexer.token_types import TokenType
        first = run[0]
        # Suppress brace expansion on a command-prefix assignment (a={x,y}).
        if (zone_active and first.type == TokenType.WORD
                and first.value and _ASSIGNMENT_RE.match(first.value)):
            return list(run)

        if len(run) == 1:
            tok = run[0]
            if (tok.type == TokenType.WORD and tok.quote_type is None
                    and tok.value and '{' in tok.value):
                try:
                    expansions = self._core._expand_braces(tok.value)
                except BraceExpansionError:
                    expansions = [tok.value]
                if not (len(expansions) == 1 and expansions[0] == tok.value):
                    # bash drops results that expand to the empty string
                    # ({a,,b} -> a b); an empty item fused with a prefix/postfix
                    # is non-empty and survives (a{,b} -> a ab). A range backslash
                    # becomes a KEPT empty word (carried as the _RANGE_EMPTY
                    # sentinel so it survives this filter), so drop only true
                    # empties, then decode the sentinel to ''.
                    expansions = [e for e in expansions if e != '']
                    expansions = [self._decode_range_empty(e) for e in expansions]
                    return self._make_word_tokens(tok, expansions)
            return list(run)

        # Composite run (adjacent tokens forming one word). Only unquoted braces
        # are structural. Expansion tokens ($((..)), $(..), $var) are carried
        # through as opaque units so brace *list* items that are expansions still
        # expand (bash: `{$((1)),$((2))}` -> `1 2`). The one case the token model
        # cannot reproduce is bash re-forming a variable *name* out of brace text
        # (`$x{1,2}` -> `$x1 $x2`); _expand_composite bails on that, leaving the
        # run unexpanded as before.
        composite = self._expand_composite(run)
        if composite is not None:
            return composite
        return list(run)

    @staticmethod
    def _decode_range_empty(value: str) -> str:
        """Replace any ``_RANGE_EMPTY`` sentinel chars with the empty string."""
        return value.replace(_RANGE_EMPTY, '')

    def _expand_composite(self, run):
        """Expand braces across a composite run of tokens.

        Encoding (so the reused string expander only treats UNQUOTED braces and
        commas as structural):
          - unquoted WORD chars  -> kept literal (their { , } .. are structural);
          - quoted chars         -> one private-use placeholder each, preserving
                                     quote type;
          - any other token      -> one private-use placeholder for the WHOLE
            (e.g. $((..)), $(..), $var)  token (opaque; never structural).
        Placeholders are decoded afterwards to rebuild each result word. Returns
        the new token list, or None if nothing expanded / the result cannot be
        represented faithfully (see the name-fusion guard below).
        """
        from ..lexer.token_types import TokenType

        # 1. Encode the run into a string of literal chars + placeholders.
        char_map = {}   # placeholder -> (char, quote_type)
        tok_map = {}    # placeholder -> whole token
        encoded = []
        next_pu = 0xE000
        for tok in run:
            if tok.type == TokenType.WORD and tok.quote_type is None:
                encoded.append(tok.value or '')
            elif tok.type in (TokenType.WORD, TokenType.STRING):
                qt = tok.quote_type
                for ch in (tok.value or ''):
                    pu = chr(next_pu); next_pu += 1
                    char_map[pu] = (ch, qt)
                    encoded.append(pu)
            else:
                pu = chr(next_pu); next_pu += 1
                tok_map[pu] = tok
                encoded.append(pu)
        encoded_str = ''.join(encoded)

        # 2. Expand using the shared core (sees only unquoted braces/commas).
        try:
            results = self._core._expand_braces(encoded_str)
        except BraceExpansionError:
            return None
        if len(results) == 1 and results[0] == encoded_str:
            return None  # nothing structural to expand

        # 3. Name-fusion guard: bash would re-form `$x` + adjacent unquoted name
        #    char into the parameter `$x<char>`; the token model keeps `$x` a
        #    separate VARIABLE token, so it cannot reproduce that. If any result
        #    places a VARIABLE token immediately before an unquoted name char,
        #    leave the whole run unexpanded (preserving prior behaviour).
        for result in results:
            for k, c in enumerate(result):
                tok = tok_map.get(c)
                if tok is not None and tok.type == TokenType.VARIABLE:
                    nxt = result[k + 1] if k + 1 < len(result) else ''
                    if nxt and nxt not in char_map and nxt not in tok_map \
                            and (nxt.isalnum() or nxt == '_'):
                        return None

        # 4. Decode each result and emit tokens. A range backslash carried as
        #    the _RANGE_EMPTY sentinel contributes nothing to a composite word
        #    (x{Z..a}y -> xy), so strip it before emitting.
        out = []
        first_word = True
        for result in results:
            result = result.replace(_RANGE_EMPTY, '')
            if not result:
                continue  # bash drops fully-empty results
            leading_adjacent = (
                getattr(run[0], 'adjacent_to_previous', False)
                if first_word else False
            )
            out.extend(self._emit_word(result, char_map, tok_map, run[0],
                                       leading_adjacent))
            first_word = False
        return out

    def _emit_word(self, result, char_map, tok_map, template, leading_adjacent):
        """Turn one expanded result (literal chars + placeholders) into tokens.

        Consecutive characters of the same quote type form one token (WORD when
        unquoted, STRING when quoted); opaque-token placeholders are emitted as
        copies of their original token. All tokens of one result word are marked
        adjacent so the parser merges them back into a single composite word.
        """
        from ..lexer.token_parts import TokenPart
        from ..lexer.token_types import TokenType

        # Build segments, uniformly 3-tuples discriminated by [0]:
        # ('chars', text, quote_type) or ('tok', token, None).
        segments: List[Tuple[str, Any, Any]] = []
        for c in result:
            if c in tok_map:
                segments.append(('tok', tok_map[c], None))
                continue
            ch, qt = char_map.get(c, (c, None))
            if segments and segments[-1][0] == 'chars' and segments[-1][2] == qt:
                segments[-1] = ('chars', segments[-1][1] + ch, qt)
            else:
                segments.append(('chars', ch, qt))

        toks = []
        for idx, seg in enumerate(segments):
            adjacent = leading_adjacent if idx == 0 else True
            if seg[0] == 'tok':
                tok = copy.copy(seg[1])
                tok.adjacent_to_previous = adjacent
                toks.append(tok)
                continue
            _, text, qt = seg
            tok = copy.copy(template)
            tok.value = text
            tok.adjacent_to_previous = adjacent
            if qt is None:
                tok.type = TokenType.WORD
                tok.quote_type = None
                tok.parts = []
            else:
                tok.type = TokenType.STRING
                tok.quote_type = qt
                tok.parts = [TokenPart(value=text, quote_type=qt)]
            toks.append(tok)
        return toks

    @staticmethod
    def _make_word_tokens(orig, values):
        toks = []
        for idx, value in enumerate(values):
            tok = copy.copy(orig)
            tok.value = value
            # The lexer's per-part metadata no longer matches the new value;
            # unquoted WORD tokens are rebuilt from `.value` downstream.
            tok.parts = []
            if idx > 0:
                # Expanded items are separate words, not a composite run.
                tok.adjacent_to_previous = False
            toks.append(tok)
        return toks
