"""Brace expansion implementation for psh.

Implements bash-style brace expansion. This module holds ``BraceExpander``, the
purely textual per-word algorithm: given a string it expands every brace
expression it contains, recursing through nesting and combining results with
their surrounding prefix/suffix. ``TokenBraceExpander`` — which applies this
algorithm across a token stream after tokenization — lives in
``brace_expansion_tokens.py`` and delegates here.

Supported forms:

- List expansion: ``{a,b,c}`` -> ``a b c``
- Numeric sequences: ``{1..10}`` -> ``1 2 3 ... 10``
- Character sequences: ``{a..z}`` -> ``a b c ... z``
- Sequences with increment: ``{1..10..2}`` -> ``1 3 5 7 9``
- Zero-padded sequences: ``{01..10}`` -> ``01 02 ... 10``
- Nested expansions: ``{{1..3},{a..c}}`` -> ``1 2 3 a b c``
- Preamble/postscript: ``file{1..3}.txt`` -> ``file1.txt file2.txt file3.txt``

The algorithm is intentionally textual: brace expansion runs *before*
parameter, command, and arithmetic expansion, so it never resolves ``$``
constructs (a list item ``$a`` is just carried through verbatim).

This module is in mypy's checked scope; keep it clean.
"""

from dataclasses import dataclass
from typing import List, Optional

from ..core.exceptions import PshError

# Default sentinel standing for a character-range element that bash emits as an
# empty (but KEPT) word. In a cross-case range like ``{Z..a}`` the backslash
# position (ASCII 92) becomes an empty string in bash, yet — unlike an empty
# *list* item (``{a,,b}`` drops it) — the empty word is preserved. We generate
# this sentinel for that position so it survives the empty-list filter, then
# decode it back to '' when emitting tokens.
#
# This is only the DEFAULT: any code point (including this one) can appear
# verbatim in user input, so ``TokenBraceExpander`` overrides ``_range_empty``
# per expansion with a code point ABSENT from the specific input — a literal
# occurrence of the default in user text is then never mistaken for the
# sentinel (F3, expansion Phase-1a). Chosen in the BMP private-use area.
_RANGE_EMPTY = ''


class BraceExpansionError(PshError):
    """Raised when brace expansion encounters an error."""
    pass


# A located brace group within a string: ``text[start:end]`` is the whole
# ``{...}`` and ``content`` is what was between the braces.
@dataclass(frozen=True)
class _BraceGroup:
    start: int   # index of the opening '{'
    end: int     # index one past the closing '}'
    content: str  # text between the braces (exclusive)


class BraceExpander:
    """Per-word brace expansion algorithm (lists, sequences, nesting).

    Used by ``TokenBraceExpander`` to expand individual words; not invoked on
    raw command lines.

    The phases, top to bottom:

    1. ``_expand_braces`` - drives repeated expansion until a fixed point.
    2. ``_expand_one_brace`` - finds and expands the leftmost brace group,
       then recombines it with its prefix/suffix.
    3. ``_find_brace_group`` - locates the first valid ``{...}``.
    4. ``_expand_list`` / ``_expand_sequence`` - generate the items for a
       group (recursing into ``_expand_braces`` for nested braces).
    """

    # Maximum number of items that can be generated by expansion
    MAX_EXPANSION_ITEMS = 10000

    #: Sentinel marking a cross-case range's backslash position as a KEPT empty
    #: word (see the module ``_RANGE_EMPTY`` note). ``TokenBraceExpander`` sets
    #: this per expansion to a code point absent from the input so a literal
    #: occurrence of the default is never treated as the sentinel (F3).
    _range_empty: str = _RANGE_EMPTY

    # ------------------------------------------------------------------ #
    # Phase 1: drive expansion to a fixed point
    # ------------------------------------------------------------------ #

    def _expand_braces(self, text: str) -> List[str]:
        """Expand all brace expressions in ``text``, returning the results.

        Each pass expands the leftmost valid brace group in every current
        result; nested braces surface on later passes, so we loop until nothing
        changes. Stray/unmatched braces are treated as literal text by
        ``_find_brace_group`` (so a valid group elsewhere still expands).
        """
        results = [text]
        while True:
            new_results: List[str] = []
            expanded_any = False

            for item in results:
                expanded = self._expand_one_brace(item)
                if self._did_expand(item, expanded):
                    expanded_any = True
                new_results.extend(expanded)

            results = new_results
            if len(results) > self.MAX_EXPANSION_ITEMS:
                raise BraceExpansionError(
                    f"Brace expansion would create {len(results)} items "
                    f"(limit: {self.MAX_EXPANSION_ITEMS})"
                )

            if not expanded_any:
                break

        return results

    @staticmethod
    def _did_expand(original: str, expanded: List[str]) -> bool:
        """True if ``_expand_one_brace`` actually changed ``original``."""
        return len(expanded) > 1 or (bool(expanded) and expanded[0] != original)

    # ------------------------------------------------------------------ #
    # Phase 2: expand the leftmost brace group and recombine
    # ------------------------------------------------------------------ #

    def _expand_one_brace(self, text: str) -> List[str]:
        """Expand the first brace expression found in ``text``.

        Returns the expanded results, or ``[text]`` unchanged if there is no
        valid brace expression (or the group turns out not to be expandable).
        """
        group = self._find_brace_group(text)
        if group is None:
            return [text]

        prefix = text[:group.start]
        suffix = text[group.end:]

        items = self._generate_items(group.content)
        if items is None:
            # Recognized as a group but not actually expandable; leave literal.
            return [text]

        # Each item carries the prefix and the WHOLE suffix; the caller re-runs
        # expansion on each result so a following group (`{a,b}{c,d}`) or a
        # literal-brace suffix (`{a,b}]` -> `a] b]`) is handled. The suffix is
        # never a real shell operator here: brace expansion runs per-WORD on the
        # token stream, so `;`/`|`/`)`/... are already separate tokens — only an
        # escaped/quoted operator can sit in a word, and that attaches (bash).
        return [prefix + item + suffix for item in items]

    def _generate_items(self, content: str) -> Optional[List[str]]:
        """Produce the items a brace group's ``content`` expands to.

        A top-level comma means a list; otherwise ``..`` means a sequence.
        Returns ``None`` when the content cannot be expanded (e.g. an invalid
        sequence), signalling the caller to leave the text literal.
        """
        if self._has_top_level_comma(content):
            return self._expand_list(content)
        if '..' in content:
            return self._expand_sequence(content)
        # Neither a list nor a sequence: not a valid brace expression.
        return None

    # ------------------------------------------------------------------ #
    # Phase 3: locate a brace group
    # ------------------------------------------------------------------ #

    def _find_brace_group(self, text: str) -> Optional[_BraceGroup]:
        """Find the first valid brace expression in ``text``.

        Scans left to right for each opening ``{`` and tries to match a valid
        ``{...}`` group starting there. ``${...}`` (a parameter expansion) is
        skipped, not treated as a brace group. Stray/unmatched braces are
        treated as literal text and do not prevent finding a valid group
        elsewhere in the word (bash: ``}{a,b}{`` -> ``}a{ }b{``); a ``{`` whose
        content is not a valid brace body, or which has no matching ``}``, is
        passed over and the search continues from the next ``{``.
        """
        i = 0
        n = len(text)
        escaped = False
        while i < n:
            char = text[i]
            if escaped:
                escaped = False
                i += 1
                continue
            if char == '\\':
                escaped = True
                i += 1
                continue

            if char == '{':
                if i > 0 and text[i - 1] == '$':
                    # Parameter expansion ${...}: skip past its close.
                    i = self._skip_parameter_expansion(text, i)
                    continue
                group = self._match_group_at(text, i)
                if group is not None:
                    return group
                # Not the start of a valid group; treat this '{' as literal
                # and keep scanning from the next character.
            i += 1

        return None

    def _match_group_at(self, text: str, open_idx: int) -> Optional[_BraceGroup]:
        """Try to match a valid ``{...}`` group whose ``{`` is at ``open_idx``.

        Tracks nested brace depth (so inner ``{...}`` pair off) and escapes,
        and locates the matching ``}`` for the opener. Returns a ``_BraceGroup``
        when one is found and its content is a valid brace body; returns
        ``None`` when there is no matching ``}`` (unclosed) or the content is
        not a valid brace expression. A ``$`` immediately before a nested ``{``
        marks a ``${...}`` whose braces are skipped wholesale.
        """
        depth = 0
        escaped = False
        i = open_idx
        n = len(text)
        while i < n:
            char = text[i]
            if escaped:
                escaped = False
                i += 1
                continue
            if char == '\\':
                escaped = True
                i += 1
                continue

            if char == '{':
                if depth > 0 and i > 0 and text[i - 1] == '$':
                    # Nested parameter expansion: skip its braces wholesale so
                    # a `}` inside it does not close our group.
                    i = self._skip_parameter_expansion(text, i)
                    continue
                depth += 1
            elif char == '}':
                depth -= 1
                if depth == 0:
                    content = text[open_idx + 1:i]
                    if self._is_valid_brace_content(content):
                        return _BraceGroup(open_idx, i + 1, content)
                    return None
            i += 1

        # No matching '}' for the opener.
        return None

    @staticmethod
    def _skip_parameter_expansion(text: str, dollar_brace_index: int) -> int:
        """Return the index just past the ``}`` closing a ``${...}``.

        ``dollar_brace_index`` points at the ``{`` of a ``${...}``. If the
        braces are unbalanced the index advances to end-of-string.
        """
        j = dollar_brace_index + 1
        brace_depth = 1
        while j < len(text) and brace_depth > 0:
            if text[j] == '{':
                brace_depth += 1
            elif text[j] == '}':
                brace_depth -= 1
            j += 1
        return j

    def _is_valid_brace_content(self, content: str) -> bool:
        """Check whether ``content`` is a valid brace expression body.

        Valid bodies have either a ``..`` range or a top-level comma (one not
        inside nested braces, and without surrounding spaces -- ``{a, b}`` is
        treated as literal text, matching bash).

        Brace expansion is purely textual and runs *before* parameter, command,
        and arithmetic expansion, so list items containing ``$var``/``$(...)``/
        ``$((...))`` still make the body valid (bash: ``{$a,$b}`` -> the words
        ``$a`` ``$b``). Ranges with ``$`` endpoints are not expandable (their
        bounds are not integers/chars at brace time) -- those are recognized as
        valid here but later return ``None`` from ``_expand_sequence``.
        """
        if not content:
            return False

        if '..' in content:
            return self._is_valid_sequence_shape(content)

        return (self._has_top_level_comma(content)
                and not self._has_spaces_around_commas(content))

    @staticmethod
    def _is_valid_sequence_shape(content: str) -> bool:
        """True if ``content`` has the shape of a range (``a..b`` / ``a..b..c``).

        Only the gross structure is checked here (2 or 3 ``..``-separated parts
        with non-empty start and end). Whether the endpoints are actually
        numeric/char sequences is decided later in ``_expand_sequence``.
        """
        parts = content.split('..')
        if not 2 <= len(parts) <= 3:
            return False
        start, end = parts[0], parts[1]
        return bool(start) and bool(end)

    # ------------------------------------------------------------------ #
    # Top-level-comma / spacing helpers (used by validation and dispatch)
    # ------------------------------------------------------------------ #

    @staticmethod
    def _has_top_level_comma(content: str) -> bool:
        """True if ``content`` has a comma outside any nested braces."""
        depth = 0
        escaped = False
        for char in content:
            if escaped:
                escaped = False
                continue
            if char == '\\':
                escaped = True
            elif char == '{':
                depth += 1
            elif char == '}':
                depth -= 1
            elif char == ',' and depth == 0:
                return True
        return False

    @staticmethod
    def _has_spaces_around_commas(content: str) -> bool:
        """True if any top-level comma in ``content`` is flanked by a space.

        Bash leaves ``{a, b, c}`` literal, so such content is rejected.
        """
        depth = 0
        escaped = False
        for i, char in enumerate(content):
            if escaped:
                escaped = False
                continue
            if char == '\\':
                escaped = True
            elif char == '{':
                depth += 1
            elif char == '}':
                depth -= 1
            elif char == ',' and depth == 0:
                before_space = i > 0 and content[i - 1] == ' '
                after_space = i < len(content) - 1 and content[i + 1] == ' '
                if before_space or after_space:
                    return True
        return False

    # ------------------------------------------------------------------ #
    # Phase 4a: list expansion
    # ------------------------------------------------------------------ #

    def _expand_list(self, content: str) -> List[str]:
        """Expand a comma-separated list body like ``a,b,c``.

        Commas inside nested braces do not split the list. Each resulting item
        is then recursively brace-expanded (so ``{a,{b,c}}`` works), with empty
        items preserved as empty strings.
        """
        items = self._split_top_level_commas(content)

        expanded_items: List[str] = []
        for item in items:
            if item == '':
                expanded_items.append('')
            else:
                expanded_items.extend(self._expand_braces(item))
        return expanded_items

    @staticmethod
    def _split_top_level_commas(content: str) -> List[str]:
        """Split ``content`` on commas that are not inside nested braces.

        Escapes and braces are tracked so ``a\\,b`` and ``a{b,c}`` are not
        split at their inner commas. Always returns at least one item.
        """
        items: List[str] = []
        current: List[str] = []
        depth = 0
        escaped = False

        for char in content:
            if escaped:
                current.append(char)
                escaped = False
                continue
            if char == '\\':
                escaped = True
                current.append(char)
            elif char == '{':
                depth += 1
                current.append(char)
            elif char == '}':
                depth -= 1
                current.append(char)
            elif char == ',' and depth == 0:
                items.append(''.join(current))
                current = []
            else:
                current.append(char)

        items.append(''.join(current))
        return items

    # ------------------------------------------------------------------ #
    # Phase 4b: sequence expansion (ranges)
    # ------------------------------------------------------------------ #

    def _expand_sequence(self, content: str) -> Optional[List[str]]:
        """Expand a range body like ``1..10`` or ``a..z`` (optionally ``..step``).

        Tries a numeric range first, then a character range. Returns ``None``
        if the body is not a valid sequence (empty bounds, non-int/non-char
        endpoints, etc.) so the caller leaves it literal.
        """
        parts = content.split('..')
        if not 2 <= len(parts) <= 3:
            return None

        start, end = parts[0], parts[1]
        increment = parts[2] if len(parts) == 3 else '1'
        if not start or not end:
            return None

        numeric_result = self._try_numeric_sequence(start, end, increment)
        if numeric_result is not None:
            return numeric_result

        return self._try_char_sequence(start, end, increment)

    @classmethod
    def _normalize_step(cls, increment: str, start_val: int, end_val: int) -> Optional[int]:
        """Parse ``increment`` into a signed, non-zero step toward ``end_val``.

        A zero step becomes 1. The sign is forced to match the direction from
        ``start_val`` to ``end_val``. Returns ``None`` if ``increment`` is not
        an integer.
        """
        try:
            step = int(increment)
        except ValueError:
            return None
        if step == 0:
            step = 1
        magnitude = abs(step)
        return magnitude if start_val <= end_val else -magnitude

    def _try_numeric_sequence(self, start: str, end: str,
                              increment: str) -> Optional[List[str]]:
        """Expand a numeric range, or return ``None`` if not numeric.

        Handles direction, zero/oversized steps, and bash's zero-padding rules
        (see ``_determine_numeric_padding`` and ``_format_padded``).
        """
        try:
            start_num = int(start)
            end_num = int(end)
        except ValueError:
            return None

        step = self._normalize_step(increment, start_num, end_num)
        if step is None:
            return None

        padding = self._determine_numeric_padding(start, end)
        crosses_zero = start_num < 0 <= end_num

        result: List[str] = []
        current = start_num
        while (step > 0 and current <= end_num) or (step < 0 and current >= end_num):
            result.append(self._format_padded(current, padding, crosses_zero))
            current += step
        return result

    @staticmethod
    def _format_padded(value: int, padding: int, crosses_zero: bool) -> str:
        """Format one numeric range element applying bash zero-padding rules.

        ``padding`` carries the calculated width from ``_determine_numeric_padding``:

        - ``0``  -> no padding;
        - ``> 0`` -> pad to that width (negatives pad the digits after ``-``;
          when the range crosses zero, zero/positive values get one extra
          digit, matching bash);
        - ``< 0`` -> special case for ``-3..03``-style ranges: only non-negative
          values are padded (to ``-padding`` digits), negatives stay bare.
        """
        if padding < 0:
            if value < 0:
                return str(value)
            return str(value).zfill(-padding)

        if padding == 0:
            return str(value)

        # padding > 0
        if value < 0:
            return '-' + str(abs(value)).zfill(padding)
        if crosses_zero:
            # Zero and positives get one extra digit when range crosses zero.
            return str(value).zfill(padding + 1)
        return str(value).zfill(padding)

    def _try_char_sequence(self, start: str, end: str,
                           increment: str) -> Optional[List[str]]:
        """Expand a single-character range like ``a..z``, or ``None`` if invalid.

        Both bounds must be single characters and both letters (cross-case
        ranges such as ``A..z`` are allowed and walk straight through the
        intervening ASCII punctuation). The backslash (ASCII 92) that falls in
        a cross-case span becomes an empty -- but kept -- word, matching bash
        (``{Z..a}`` -> ``Z [`` `` ``] ^ _ ` a``); it is emitted as the
        ``_RANGE_EMPTY`` sentinel so it survives the empty-list filter and is
        decoded to '' at token-emit time.
        """
        if len(start) != 1 or len(end) != 1:
            return None
        if not (start.isalpha() and end.isalpha()):
            return None

        step = self._normalize_step(increment, ord(start), ord(end))
        if step is None:
            return None

        start_ord, end_ord = ord(start), ord(end)
        result: List[str] = []
        current = start_ord
        while (step > 0 and current <= end_ord) or (step < 0 and current >= end_ord):
            ch = chr(current)
            result.append(self._range_empty if ch == '\\' else ch)
            current += step
        return result

    @staticmethod
    def _determine_numeric_padding(start: str, end: str) -> int:
        """Compute the zero-padding width for a numeric range.

        Returns:
        - ``0`` when neither endpoint is zero-padded;
        - the max endpoint digit-width when padding applies;
        - a negative ``-len(end_digits)`` to flag the ``-3..03`` special case
          (negative start without padding, padded positive end), which
          ``_format_padded`` interprets as "pad positives only".
        """
        start_digits = start.lstrip('-+')
        end_digits = end.lstrip('-+')

        has_start_padding = len(start_digits) > 1 and start_digits.startswith('0')
        has_end_padding = len(end_digits) > 1 and end_digits.startswith('0')
        if not (has_start_padding or has_end_padding):
            return 0

        # Negative unpadded start with a padded end: only positives get padded.
        if int(start) < 0 and not has_start_padding and has_end_padding:
            return -len(end_digits)

        return max(len(start_digits), len(end_digits))

    # ------------------------------------------------------------------ #
    # Misc
    # ------------------------------------------------------------------ #

    def _contains_expandable_dollar(self, content: str) -> bool:
        """Check if ``content`` contains a real ``$`` expansion pattern.

        True for ``$var``/``${var}`` (variables), ``$(cmd)`` (command sub),
        ``$((expr))`` (arithmetic), and special variables (``$1``, ``$@`` ...).
        False for a bare ``$`` (at end of string, or before a comma/other
        non-variable character, as in ``{$,#,@}``).
        """
        i = 0
        n = len(content)
        while i < n:
            if content[i] != '$':
                i += 1
                continue
            if i + 1 >= n:
                # Trailing '$': not an expansion.
                i += 1
                continue
            next_char = content[i + 1]
            if next_char in '{(':
                return True
            if next_char.isalpha() or next_char == '_':
                return True
            if next_char == ',':
                # '$' before a comma is literal, e.g. {$,#,@}.
                i += 1
                continue
            if next_char.isdigit() or next_char in '@*#?-!$':
                return True
            i += 1
        return False
