"""Token-stream brace expansion for psh.

``TokenBraceExpander`` applies the textual brace-expansion algorithm
(:class:`~psh.expansion.brace_expansion.BraceExpander`) across a token
stream *after* tokenization, rather than expanding the raw command text and
re-lexing the result. Working on tokens means:

- characters generated by a range (e.g. the backtick in ``{Z..a}``) stay
  literal — nothing is re-lexed;
- quote context is already resolved by the lexer;
- assignment words can be left unexpanded using command-prefix position
  (bash: ``a={x,y}`` stays literal, but ``echo a={x,y}`` expands);
- ``[[ ... ]]`` regions can be left unexpanded entirely (bash performs no
  brace expansion inside the conditional expression, so regex intervals like
  ``[[ 192 =~ ^[0-9]{1,3}$ ]]`` and patterns like ``a{b,c}`` stay literal).

It delegates the actual per-string expansion to ``BraceExpander``; this module
only handles the token-stream concerns (run gathering, quote/opaque-token
encoding, command-prefix and ``[[ ]]``-region tracking).

Out-of-band metadata (INTERIM design, F3 / expansion Phase-1a): composite runs
and the range-empty marker are carried through the core expander as single
placeholder characters embedded in the string. Because any code point can
appear verbatim in user input, those placeholders are chosen per expansion to
AVOID every code point present in the run (see ``_first_free_codepoint``), so a
literal ``U+E000``/``U+F8FF`` is never mistaken for a sentinel and deleted or
misdecoded. This escape-free "dodge the input" scheme is collision-proof but
still in-band; the intended end state is to move brace expansion into the
structured ``Word`` stage so metadata is genuinely out-of-band (expansion
improvement-plan finding 3, "preferred design"; a later cross-doc campaign).

This module is in mypy's checked scope; keep it clean.
"""

import copy
import re
from typing import Any, List, Tuple

from ..core.assignment_utils import ASSIGNMENT_WORD_RE, NAME_RE
from .brace_expansion import BraceExpander, BraceExpansionError


def _first_free_codepoint(forbidden: set, start: int = 0xE000) -> str:
    """A code point (private-use area upward) not present in ``forbidden``.

    Brace expansion carries out-of-band metadata — the range-empty sentinel and
    the composite-run placeholders — as single characters inside the string it
    hands the core expander. Because ANY code point can appear verbatim in user
    input, those sentinels must avoid the code points actually present, or a
    literal ``U+F8FF``/``U+E000`` would collide and be deleted or misdecoded
    (F3, expansion Phase-1a). Generated range elements are always ASCII, so
    starting in the BMP private-use area (``U+E000``) also keeps sentinels clear
    of them.
    """
    cp = start
    while cp <= 0x10FFFF:
        if cp not in forbidden:
            return chr(cp)
        cp += 1
    raise BraceExpansionError(
        "brace expansion: no free sentinel code point")

# Assignment words (name=, name[idx]=, name+=) share the canonical
# ASSIGNMENT_WORD_RE: brace expansion is suppressed on them in command-prefix
# position (bash: `a={x,y}` stays literal, but `echo a={x,y}` expands).
#
# A simple (fusable) variable name uses the canonical NAME_RE: `$v{1,2}`
# re-forms the names `v1`/`v2` in bash because brace expansion runs first.
# Braced `${v}`, special ($?, $#) and positional ($1) parameters are delimited
# and never fuse.
_NAME_CHARS_RE = re.compile(r'[A-Za-z0-9_]+')


class TokenBraceExpander:
    """Brace expansion performed on a token stream (post-tokenization).

    This replaces expanding the raw command text and re-lexing the result.
    Working on tokens means:

    - characters generated by a range (e.g. the backtick in ``{Z..a}``) stay
      literal — nothing is re-lexed (fixes the re-lex crash);
    - quote context is already resolved by the lexer;
    - assignment words can be left unexpanded using command-prefix position.

    Standalone unquoted ``WORD`` tokens expand directly; composite runs
    (adjacent tokens forming one word, e.g. ``"$f"{1,2}``) go through
    ``_expand_composite``, which preserves quote context and expansion
    metadata across the expansion.
    """

    def __init__(self):
        self._core = BraceExpander()

    # Token types that glue to a neighbour to form one composite word.
    def _word_like(self):
        from ..lexer.token_types import TokenType
        return {
            TokenType.WORD, TokenType.STRING, TokenType.VARIABLE,
            TokenType.COMMAND_SUB, TokenType.COMMAND_SUB_BACKTICK,
            TokenType.ARITH_EXPANSION,
            TokenType.PROCESS_SUB_IN, TokenType.PROCESS_SUB_OUT,
        }

    def _reset_types(self):
        from ..lexer.token_types import TokenType
        return {
            TokenType.SEMICOLON, TokenType.NEWLINE, TokenType.AND_AND,
            TokenType.OR_OR, TokenType.PIPE, TokenType.DOUBLE_SEMICOLON,
            TokenType.SEMICOLON_AMP, TokenType.AMP_SEMICOLON,
            TokenType.AMPERSAND, TokenType.THEN, TokenType.DO, TokenType.ELSE,
            TokenType.ELIF, TokenType.FI, TokenType.DONE, TokenType.ESAC,
            TokenType.LPAREN, TokenType.RPAREN, TokenType.LBRACE,
            TokenType.RBRACE, TokenType.IF, TokenType.WHILE, TokenType.UNTIL,
        }

    def expand(self, tokens, enabled=True):
        """Expand braces across ``tokens``.

        ``enabled`` seeds the braceexpand state from the live shell option
        (bash ``set -B``/``+B``, on by default). Because psh brace-expands at
        tokenize time while bash does it at word-expansion time, a ``set``
        that toggles the option DURING this token stream would otherwise only
        take effect for the NEXT parse unit. So — mirroring the same-stream
        ``alias`` absorption in AliasManager — a command-position ``set``
        whose literal arguments toggle braceexpand (``-B``/``+B`` clusters,
        ``-o``/``+o braceexpand``), or a command-position ``shopt`` whose
        flags combine ``o`` with ``s``/``u`` over a ``braceexpand`` operand
        (``shopt -so/-uo braceexpand`` == ``set -o/+o braceexpand``, v0.674),
        flips the state for the REST of the stream,
        making straight-line code (``set +B; echo {a,b}``) match bash. The
        toggle applies AFTER the toggling command's own words (bash expands a
        command's words before running it), is discarded when the command is
        a pipeline segment or backgrounded (a subshell in bash), and is
        scoped across ``( ... )`` subshells.

        Known approximation (parse-time model; ledgered — the real fix is
        moving brace expansion into the Word stage): a toggle inside a
        not-taken branch or a not-called function definition still flips the
        rest of the SAME parse unit, and loop bodies are expanded once with
        the state at their position rather than per iteration. The scanner
        also fires on a ``set``/``shopt`` that will not run as the builtin (a
        function-shadowed one), misses one that runs as a LATER pipeline
        segment (``true | set +B`` — bash subshells it, so nothing should
        toggle), skips invalid cluster letters that would make the real
        builtin abort (``set -zB``, ``shopt -zso braceexpand``), and does not
        interpret quoted or dynamic arguments (``shopt -so "braceexpand"``
        toggles in bash but not same-line here). All of these are
        same-parse-unit-only:
        subsequent parse units always use the runtime option value.
        """
        if not tokens:
            return tokens
        from ..lexer.token_types import TokenType

        word_like = self._word_like()
        reset_types = self._reset_types()

        out = []
        zone_active = True  # in a command-prefix (assignment-allowed) position
        in_test_expr = False  # between [[ and ]] — no brace expansion there
        pending_toggle = None   # braceexpand state to adopt after this command
        paren_stack = []        # enabled-state saved at each `(` (subshell scope)
        n = len(tokens)
        i = 0

        while i < n:
            tok = tokens[i]
            if tok.type == TokenType.DOUBLE_LBRACKET:
                # Bash performs NO brace expansion inside [[ ... ]]: regex
                # intervals ([[ x =~ [0-9]{1,3} ]]) and patterns (a{b,c})
                # stay literal. The lexer only emits DOUBLE_LBRACKET in
                # command position, so the token type marks the region
                # reliably. [[ ]] does not nest (an inner `[[` is a WORD),
                # so a flag suffices; an unbalanced `[[` — a parse error
                # downstream — merely leaves the rest unexpanded.
                in_test_expr = True
                out.append(tok)
                i += 1
            elif tok.type == TokenType.DOUBLE_RBRACKET:
                # ]] terminates the conditional like `)`/`}` end their
                # compounds, so it also reopens the command prefix.
                in_test_expr = False
                zone_active = True
                out.append(tok)
                i += 1
            elif in_test_expr:
                out.append(tok)
                i += 1
            elif tok.type in (TokenType.HEREDOC, TokenType.HEREDOC_STRIP):
                # A heredoc delimiter is taken LITERALLY — bash performs no
                # brace expansion on it (`cat <<E{a,b}F` waits for the literal
                # terminator line `E{a,b}F`). Copy the operator and its
                # adjacent delimiter-word run through unexpanded; expanding
                # here would also detach the word from the terminator the
                # HeredocCollector registered from the raw source.
                out.append(tok)
                j = i + 1
                if j < n and tokens[j].type in word_like:
                    out.append(tokens[j])
                    while (j + 1 < n and tokens[j + 1].type in word_like
                           and getattr(tokens[j + 1], 'adjacent_to_previous',
                                       False)):
                        j += 1
                        out.append(tokens[j])
                    j += 1
                i = j
            elif tok.type in word_like:
                # Gather a maximal run of adjacent word-forming tokens — these
                # together form one logical (possibly composite) word.
                j = i
                while (j + 1 < n and tokens[j + 1].type in word_like
                       and getattr(tokens[j + 1], 'adjacent_to_previous', False)):
                    j += 1
                run = tokens[i:j + 1]
                if enabled:
                    out.extend(self._expand_run(run, zone_active))
                else:
                    out.extend(run)
                # A command-position `set` or `shopt` may toggle braceexpand
                # for the rest of this stream (see the expand() docstring).
                if (zone_active and len(run) == 1
                        and tok.type == TokenType.WORD
                        and tok.quote_type is None
                        and tok.value in ('set', 'shopt')):
                    if tok.value == 'set':
                        toggle = self._interpret_set_args(tokens, j + 1, n)
                    else:
                        toggle = self._interpret_shopt_args(tokens, j + 1, n)
                    if toggle is not None:
                        pending_toggle = toggle
                zone_active = self._zone_after_word(run[0], zone_active)
                i = j + 1
            else:
                out.append(tok)
                if tok.type in reset_types:
                    zone_active = True
                    if tok.type == TokenType.LPAREN:
                        if pending_toggle is not None:  # malformed source
                            enabled, pending_toggle = pending_toggle, None
                        paren_stack.append(enabled)
                    elif tok.type == TokenType.RPAREN:
                        # A subshell's toggle does not escape it (bash).
                        pending_toggle = None
                        if paren_stack:
                            enabled = paren_stack.pop()
                    elif tok.type in (TokenType.PIPE, TokenType.AMPERSAND):
                        # A pipeline segment / background command runs in a
                        # subshell in bash — its `set` does not persist.
                        pending_toggle = None
                    elif pending_toggle is not None:
                        enabled, pending_toggle = pending_toggle, None
                i += 1

        return out

    def _interpret_set_args(self, tokens, start, n):
        """Best-effort static read of a `set` command's braceexpand effect.

        Scans the argument tokens from ``start`` up to the command's end,
        interpreting only plain, unquoted, single-token literal words —
        scanning stops conservatively at the first argument it cannot read
        statically (an expansion, a quoted or composite word, a redirect).
        Recognized toggles: ``B`` in a ``-``/``+`` cluster, and a cluster
        ending in ``o`` whose following name is ``braceexpand``. Returns
        True (enable) / False (disable) / None (no toggle seen). The RUNTIME
        option value is still owned by SetBuiltin — this only keeps the
        current token stream's expansion in step with it.
        """
        from ..lexer.token_types import TokenType
        word_like = self._word_like()
        reset_types = self._reset_types()
        toggle = None
        expect_o_name = None  # sign of a trailing-`o` cluster awaiting its name
        j = start
        while j < n and tokens[j].type not in reset_types:
            tok = tokens[j]
            composite = (j + 1 < n and tokens[j + 1].type in word_like
                         and getattr(tokens[j + 1], 'adjacent_to_previous',
                                     False))
            if (tok.type != TokenType.WORD or tok.quote_type is not None
                    or composite):
                break  # not a plain literal word: stop interpreting
            word = tok.value or ''
            if expect_o_name is not None:
                if word == 'braceexpand':
                    toggle = (expect_o_name == '-')
                expect_o_name = None
                j += 1
                continue
            if word in ('--', '-', '+'):
                break  # end of options: the rest are positional parameters
            if word[:1] in ('-', '+') and len(word) > 1:
                sign = word[0]
                cluster = word[1:]
                for pos, ch in enumerate(cluster):
                    if ch == 'o' and pos == len(cluster) - 1:
                        expect_o_name = sign
                    elif ch == 'B':
                        toggle = (sign == '-')
            else:
                break  # first non-option argument: positional parameters
            j += 1
        return toggle

    def _interpret_shopt_args(self, tokens, start, n):
        """Best-effort static read of a `shopt` command's braceexpand effect.

        The `shopt -o` mode operates on the set -o option table, so
        ``shopt -so/-uo braceexpand`` toggles brace expansion exactly like
        ``set -o/+o braceexpand`` — including for the rest of the SAME
        stream. Grammar (probe-pinned vs bash 5.2, tmp/optreflect/probe3):
        flag clusters only BEFORE the first operand (a later ``-uo`` is an
        operand), ``--`` ends flags, and a toggle needs ``o`` together with
        exactly ONE of ``s``/``u`` (the real shopt aborts on ``-s`` with
        ``-u``) plus a literal ``braceexpand`` operand. ``-p``/``-q`` don't
        suppress it (bash: ``shopt -pso braceexpand`` still sets); an
        invalid sibling operand doesn't derail it (bash applies the valid
        names). ``shopt -s braceexpand`` WITHOUT ``-o`` is NOT a toggle —
        braceexpand is not a shopt-table name.

        Same conservatism as :meth:`_interpret_set_args`: only plain,
        unquoted, single-token literal words are interpreted; scanning
        stops at the first argument it cannot read statically.
        """
        from ..lexer.token_types import TokenType
        word_like = self._word_like()
        reset_types = self._reset_types()
        has_s = has_u = has_o = False
        saw_braceexpand = False
        in_operands = False
        j = start
        while j < n and tokens[j].type not in reset_types:
            tok = tokens[j]
            composite = (j + 1 < n and tokens[j + 1].type in word_like
                         and getattr(tokens[j + 1], 'adjacent_to_previous',
                                     False))
            if (tok.type != TokenType.WORD or tok.quote_type is not None
                    or composite):
                break  # not a plain literal word: stop interpreting
            word = tok.value or ''
            if not in_operands and word == '--':
                in_operands = True
            elif not in_operands and word[:1] == '-' and len(word) > 1:
                for ch in word[1:]:
                    if ch == 's':
                        has_s = True
                    elif ch == 'u':
                        has_u = True
                    elif ch == 'o':
                        has_o = True
                    # p/q and even invalid letters are ignored — the same
                    # approximation family as _interpret_set_args (see the
                    # expand() docstring).
            else:
                in_operands = True
                if word == 'braceexpand':
                    saw_braceexpand = True
            j += 1
        if has_o and saw_braceexpand and (has_s != has_u):
            return has_s
        return None

    def _zone_after_word(self, first_tok, zone_active):
        from ..lexer.token_types import TokenType
        # An assignment word keeps the command prefix open (a=1 b=2 cmd); any
        # other word is the command name (or an argument) and ends the prefix.
        if (first_tok.type == TokenType.WORD and zone_active
                and first_tok.value and ASSIGNMENT_WORD_RE.match(first_tok.value)):
            return True
        return False

    def _expand_run(self, run, zone_active):
        from ..lexer.token_types import TokenType
        first = run[0]
        # Suppress brace expansion on a command-prefix assignment (a={x,y}).
        if (zone_active and first.type == TokenType.WORD
                and first.value and ASSIGNMENT_WORD_RE.match(first.value)):
            return list(run)

        if len(run) == 1:
            tok = run[0]
            if (tok.type == TokenType.WORD and tok.quote_type is None
                    and tok.value and '{' in tok.value):
                # Pick a range-empty sentinel absent from this word so a
                # literal occurrence of the default is not stripped (F3).
                range_empty = _first_free_codepoint(set(map(ord, tok.value)))
                self._core._range_empty = range_empty
                # A budget overflow (BraceExpansionError) is NOT caught here:
                # it propagates as a loud SyntaxError-class diagnostic instead
                # of the old silent restore-the-literal behavior (F4).
                expansions = self._core._expand_braces(tok.value)
                if not (len(expansions) == 1 and expansions[0] == tok.value):
                    # bash drops results that expand to the empty string
                    # ({a,,b} -> a b); an empty item fused with a prefix/postfix
                    # is non-empty and survives (a{,b} -> a ab). A range backslash
                    # becomes a KEPT empty word (carried as the range-empty
                    # sentinel so it survives this filter), so drop only true
                    # empties, then decode the sentinel to ''.
                    expansions = [e for e in expansions if e != '']
                    expansions = [e.replace(range_empty, '') for e in expansions]
                    return self._make_word_tokens(tok, expansions)
            return list(run)

        # Composite run (adjacent tokens forming one word). Only unquoted braces
        # are structural. Expansion tokens ($((..)), $(..), $var) are carried
        # through as opaque units so brace *list* items that are expansions still
        # expand (bash: `{$((1)),$((2))}` -> `1 2`), and quoted tokens keep
        # their per-part expansion metadata (`"$f"{1,2}` -> `F1 F2`).
        composite = self._expand_composite(run)
        if composite is not None:
            return composite
        return list(run)

    def _expand_composite(self, run):
        """Expand braces across a composite run of tokens.

        Encoding (so the reused string expander only treats UNQUOTED braces and
        commas as structural):
          - unquoted WORD chars   -> kept literal (their { , } .. are structural);
          - quoted literal chars  -> one private-use placeholder each, preserving
                                      quote type;
          - quoted expansion part -> one placeholder for the WHOLE TokenPart
            (e.g. the `$f` inside `"$f.txt"`), so its expansion metadata
            survives the rebuild;
          - any other token       -> one placeholder for the WHOLE token
            (e.g. $((..)), $(..), $var)  (opaque; never structural).
        Placeholders are decoded afterwards to rebuild each result word. Returns
        the new token list, or None if nothing expanded.

        Placeholders and the range-empty sentinel are chosen to AVOID every code
        point present in the run, so a literal private-use character in the input
        (e.g. U+E000, U+F8FF) is never mistaken for one and corrupted (F3).
        """
        from ..lexer.token_types import TokenType

        # 1. Encode the run into a string of literal chars + placeholders.
        char_map = {}   # placeholder -> (text, quote_type); '' = quoted empty
        part_map = {}   # placeholder -> (TokenPart expansion, quote_type)
        tok_map = {}    # placeholder -> whole token
        encoded = []
        # Code points already present verbatim in the run: placeholders and the
        # range-empty sentinel must dodge these (generated range elements are
        # always ASCII, so the private-use start also keeps them clear of those).
        forbidden = {ord(c) for tok in run for c in (tok.value or '')}
        next_cp = [0xE000]

        def new_placeholder():
            cp = next_cp[0]
            while cp in forbidden:
                cp += 1
            if cp > 0x10FFFF:
                raise BraceExpansionError(
                    "brace expansion: no free placeholder code point")
            next_cp[0] = cp + 1
            return chr(cp)

        # Reserve the range-empty sentinel first, so it collides with neither a
        # placeholder nor an input code point.
        range_empty = new_placeholder()
        self._core._range_empty = range_empty

        for tok in run:
            if tok.type == TokenType.WORD and tok.quote_type is None:
                encoded.append(tok.value or '')
            elif tok.type in (TokenType.WORD, TokenType.STRING):
                qt = tok.quote_type
                token_encoded = []
                for part in (getattr(tok, 'parts', None) or []):
                    pqt = part.quote_type if part.quote_type is not None else qt
                    if part.is_expansion:
                        pu = new_placeholder()
                        part_map[pu] = (part, pqt)
                        token_encoded.append(pu)
                    else:
                        for ch in part.value:
                            pu = new_placeholder()
                            char_map[pu] = (ch, pqt)
                            token_encoded.append(pu)
                if not token_encoded:
                    for ch in (tok.value or ''):  # token without part metadata
                        pu = new_placeholder()
                        char_map[pu] = (ch, qt)
                        token_encoded.append(pu)
                if not token_encoded:
                    # `""`: a quoted-empty marker so the item survives the
                    # empty-result filter (bash: `{a,""}` keeps the empty word).
                    pu = new_placeholder()
                    char_map[pu] = ('', qt)
                    token_encoded.append(pu)
                encoded.extend(token_encoded)
            else:
                pu = new_placeholder()
                tok_map[pu] = tok
                encoded.append(pu)
        encoded_str = ''.join(encoded)

        # 2. Expand using the shared core (sees only unquoted braces/commas).
        #    A budget overflow propagates loudly (F4); it is not swallowed
        #    into a silent literal restore.
        results = self._core._expand_braces(encoded_str)
        if len(results) == 1 and results[0] == encoded_str:
            return None  # nothing structural to expand

        # 3. Decode each result and emit tokens. A range backslash carried as
        #    the range-empty sentinel contributes nothing to a composite word
        #    (x{Z..a}y -> xy), so strip it before emitting.
        out = []
        first_word = True
        for result in results:
            result = result.replace(range_empty, '')
            if not result:
                continue  # bash drops fully-empty results
            leading_adjacent = (
                getattr(run[0], 'adjacent_to_previous', False)
                if first_word else False
            )
            out.extend(self._emit_word(result, char_map, part_map, tok_map,
                                       run[0], leading_adjacent))
            first_word = False
        return out

    def _emit_word(self, result, char_map, part_map, tok_map, template,
                   leading_adjacent):
        """Turn one expanded result (literal chars + placeholders) into tokens.

        Consecutive quoted parts of the same quote type form one STRING token
        (carrying the original expansion TokenParts, so `"$f"{1,2}` still
        expands `$f` downstream); unquoted chars form WORD tokens; opaque-token
        placeholders are emitted as copies of their original token. All tokens
        of one result word are marked adjacent so the parser merges them back
        into a single composite word.
        """
        from ..lexer.token_parts import TokenPart
        from ..lexer.token_types import TokenType

        # Build segments, uniformly 3-tuples discriminated by [0]:
        # ('chars', text, None)        unquoted literal text
        # ('str', [TokenPart...], qt)  quoted run of one quote type
        # ('tok', token, None)         opaque whole token
        segments: List[Tuple[str, Any, Any]] = []

        def append_quoted(part: 'TokenPart', qt) -> None:
            if segments and segments[-1][0] == 'str' and segments[-1][2] == qt:
                segments[-1][1].append(part)
            else:
                segments.append(('str', [part], qt))

        for c in result:
            if c in tok_map:
                segments.append(('tok', tok_map[c], None))
            elif c in part_map:
                part, qt = part_map[c]
                append_quoted(copy.copy(part), qt)
            else:
                ch, qt = char_map.get(c, (c, None))
                if qt is None:
                    if segments and segments[-1][0] == 'chars':
                        segments[-1] = ('chars', segments[-1][1] + ch, None)
                    else:
                        segments.append(('chars', ch, None))
                else:
                    last = segments[-1][1] if (segments
                                               and segments[-1][0] == 'str'
                                               and segments[-1][2] == qt) else None
                    if last and not last[-1].is_expansion:
                        last[-1] = TokenPart(value=last[-1].value + ch,
                                             quote_type=qt)
                    else:
                        append_quoted(TokenPart(value=ch, quote_type=qt), qt)

        toks: List[Any] = []
        i = 0
        while i < len(segments):
            kind, payload, qt = segments[i]
            adjacent = leading_adjacent if not toks else True
            tok = copy.copy(payload) if kind == 'tok' else copy.copy(template)
            if kind == 'tok':
                # Brace expansion precedes parameter expansion in bash, so
                # `$v{1,2}` re-forms the names `v1`/`v2`: fold trailing
                # unquoted name chars into a simple-name VARIABLE.
                if (tok.type == TokenType.VARIABLE and tok.value
                        and NAME_RE.match(tok.value)
                        and i + 1 < len(segments)
                        and segments[i + 1][0] == 'chars'):
                    m = _NAME_CHARS_RE.match(segments[i + 1][1])
                    if m:
                        tok.value += m.group(0)
                        rest = segments[i + 1][1][m.end():]
                        if rest:
                            segments[i + 1] = ('chars', rest, None)
                        else:
                            del segments[i + 1]
            elif kind == 'chars':
                tok.type = TokenType.WORD
                tok.value = payload
                tok.quote_type = None
                tok.parts = []
            else:  # 'str'
                tok.type = TokenType.STRING
                tok.value = ''.join(self._part_source(p) for p in payload)
                tok.quote_type = qt
                tok.parts = payload
            tok.adjacent_to_previous = adjacent
            toks.append(tok)
            i += 1
        return toks

    @staticmethod
    def _part_source(part) -> str:
        """Source text a TokenPart contributes to its token's value."""
        if part.is_expansion and part.expansion_type == 'variable':
            return '$' + part.value  # variable parts store the bare name
        return part.value  # other parts keep their full source syntax

    @staticmethod
    def _make_word_tokens(orig, values):
        toks = []
        for idx, value in enumerate(values):
            tok = copy.copy(orig)
            tok.value = value
            # The lexer's per-part metadata no longer matches the new value;
            # unquoted WORD tokens are rebuilt from `.value` downstream.
            tok.parts = []
            if idx > 0:
                # Expanded items are separate words, not a composite run.
                tok.adjacent_to_previous = False
            toks.append(tok)
        return toks
