def test_pipeline_member_suppression_matches_bash():
    """A pipeline MEMBER inherits the enclosing list's errexit suppression only
    through a COMPOUND command or a function BODY — never into its own simple
    command. bash's rule, and the reason a single flag cannot express it.

    THE BASH SENTENCE this pins (manual, "The Set Builtin"): "If a compound
    command or shell function executes in a context where -e is being ignored,
    none of the commands executed within the compound command or function body
    will be affected by the -e setting." A SIMPLE-COMMAND member introduces no
    such body, so ``set -e`` stays effective for the text its ``eval``/``.``
    parses, and the substitution abort lands on the errexit branch (2). A
    ``{ }`` / ``( )`` / function / ``if`` / ``while`` / ``for`` / ``case``
    member does introduce one, so the suppression reaches it (1).

    WHY THE HISTORY MATTERS HERE: round 4 gave the launcher-leaf child an
    unsuppressed context by default, which satisfied the simple-member rows;
    round 5 replaced that with a stamp read from the inherited depth, which
    satisfied the compound-member rows and REGRESSED the simple ones — 21 rows
    across suppression source, error kind, spelling, member position and
    prefix. Neither end of the branch satisfied both, which is why this pin
    carries the compound shapes as CONTROLS in the same function: a future
    change that fixes one half by breaking the other fails here, not in a
    verification round.

    A SECOND, INDEPENDENT DISCRIMINATOR agrees with every row below and is
    worth recording even though it is not asserted (stderr wording is not a
    pinned surface): bash prints ONE stderr line for these shapes when errexit
    is EFFECTIVE and TWO when it is ignored.

    DOMAIN, and what this pin SAMPLES of it. The regression family measured at
    the stamp commit is 21 rows = {suppression source: ``||``, ``&&``
    non-final, ``if`` condition} x {error kind: unclosed ``$(if)``,
    complete-but-invalid ``$(fi)``} x {spelling: cmdsub, procsub, ``.`` file}
    x {member position: final, non-final, middle-of-three} x {bare, ``command``
    prefix, assignment prefix, redirected}. The rows below SAMPLE that space
    (they are not its cross product); the exhaustive evidence is the chain
    table, which carries every row at bash / base 1b271d77 / round-4 f0cc466e /
    tip: ``tmp/r24-probes/r6b-CHAIN-*.txt``, generated by ``r6b*.py``.

    RED-ON-360090b2 for the simple-member rows (the stamp commit answered 1);
    the compound and function rows below were ALREADY green there and are
    carried as MUST-NOT-MOVE guards for this fix, because the two halves have
    never yet been green at the same commit.

    Measured over bash 5.2.26, both parsers, all three channels."""
    # --- the SIMPLE-COMMAND member: errexit stays effective -> 2 ------------
    simple_rows = [
        # suppression sources
        "set -e\n{ true | eval 'echo $(if)'; } || echo GOT rc=$?",
        "set -e\nif true | eval 'echo $(if)'; then echo T; else echo GOT rc=$?; fi",
        "set -e\n{ true | eval 'echo $(if)'; } && echo T\necho GOT rc=$?",
        # the other error kind, and the other two spellings
        "set -e\n{ true | eval 'echo $(fi)'; } || echo GOT rc=$?",
        "set -e\n{ true | eval 'cat <(if)'; } || echo GOT rc=$?",
        # prefixes and a redirect do not change the member's KIND
        "set -e\n{ true | command eval 'echo $(if)'; } || echo GOT rc=$?",
        "set -e\n{ true | X=1 eval 'echo $(if)'; } || echo GOT rc=$?",
        "set -e\n{ true | eval 'echo $(if)' 2>/dev/null; } || echo GOT rc=$?",
    ]
    for script in simple_rows:
        for channel in ("c", "file", "stdin"):
            b, p = _bash(script, channel), _psh(script, channel)
            assert b.stdout == p.stdout, (script, channel, b.stdout, p.stdout)
            assert "rc=2" in p.stdout, (script, channel, p.stdout)

    # --- the NON-FINAL member: same rule, read through PIPESTATUS ----------
    for script in ["set -e\neval 'echo $(if)' | cat || echo GOT\necho PS=${PIPESTATUS[*]}",
                   "set -e\ntrue | eval 'echo $(if)' | cat || echo GOT\necho PS=${PIPESTATUS[*]}"]:
        for channel in ("c", "file"):
            b, p = _bash(script, channel), _psh(script, channel)
            assert b.stdout == p.stdout, (script, channel, b.stdout, p.stdout)
            assert " 2" in p.stdout or "=2" in p.stdout, (script, p.stdout)

    # --- CONTROLS: a COMPOUND or FUNCTION member DOES inherit it -> 1 ------
    compound_rows = [
        "set -e\n{ true | { eval 'echo $(if)'; }; } || echo GOT rc=$?",
        "set -e\n{ true | ( eval 'echo $(if)' ); } || echo GOT rc=$?",
        "set -e\n{ true | if true; then eval 'echo $(if)'; fi; } || echo GOT rc=$?",
        "set -e\n{ true | while :; do eval 'echo $(if)'; break; done; } || echo GOT rc=$?",
        "set -e\n{ true | for x in 1; do eval 'echo $(if)'; done; } || echo GOT rc=$?",
        "set -e\n{ true | case x in x) eval 'echo $(if)';; esac; } || echo GOT rc=$?",
        # a function reached through an EXPANSION: the rule is applied at
        # BODY entry, so it cannot be decided from the member's AST alone.
        "f() { eval 'echo $(if)'; }\nQ=f\nset -e\n{ true | $Q; } || echo GOT rc=$?",
    ]
    for script in compound_rows:
        for channel in ("file", "stdin"):
            b, p = _bash(script, channel), _psh(script, channel)
            assert b.stdout == p.stdout, (script, channel, b.stdout, p.stdout)
            assert "rc=1" in p.stdout, (script, channel, p.stdout)

    # --- CONTROLS: with the enclosing pipeline UNSUPPRESSED every member
    #     shape is 2, which is what proves the rows above are INHERITANCE
    #     and not a blanket clear. ------------------------------------------
    for member in ["eval 'echo $(if)'", "{ eval 'echo $(if)'; }",
                   "( eval 'echo $(if)' )"]:
        script = "set -e\n{ true | %s; }\necho AFTER rc=$?" % member
        for channel in ("c", "file"):
            b, p = _bash(script, channel), _psh(script, channel)
            assert b.returncode == p.returncode == 2, (script, channel, b, p)
            assert b.stdout == p.stdout == "", (script, channel, b.stdout)

    # --- CONTROLS: the OTHER readers of the suppression depth are unmoved --
    # the POSIX special-builtin suppressible exit, and an ordinary failure.
    for script, expected in [
        ("set -o posix\nset -e\n{ true | set -q; } || echo GOT rc=$?\necho AFTER",
         "GOT rc=2\nAFTER\n"),
        ("set -e\n{ true | false; } || echo GOT rc=$?", "GOT rc=1\n"),
    ]:
        for channel in ("c", "file"):
            b, p = _bash(script, channel), _psh(script, channel)
            assert b.stdout == p.stdout == expected, (script, channel,
                                                      b.stdout, p.stdout)
