#!/bin/sh
# Q3 static censuses at ae871a16 (run with cwd = worktree).
# Each count is generated by the command that records it.
set -u
cd "/private/tmp/claude-501/-Users-pwilson-src-psh/05736dde-f3cd-4b98-98df-9708e107bca4/scratchpad/ckr/q3/wt" || exit 1
echo "== HEAD =="; git rev-parse HEAD

echo "== C1: .as_scalar( call sites in psh/ (independent sweep vs RULED_PROJECTIONS) =="
grep -rn "\.as_scalar(" psh/ --include='*.py'
echo "count: $(grep -rn '\.as_scalar(' psh/ --include='*.py' | wc -l | tr -d ' ')"

echo "== C2: _owed writers — everything touching _owed in psh/ =="
grep -rn "_owed" psh/ --include='*.py'
echo "files: $(grep -rln '_owed' psh/ --include='*.py' | tr '\n' ' ')"

echo "== C3: _file_synced_len occurrences in psh/ (must be ZERO — retired) =="
grep -rn "_file_synced_len" psh/ --include='*.py'; echo "count: $(grep -rn '_file_synced_len' psh/ --include='*.py' | wc -l | tr -d ' ')"

echo "== C4: strict=True in the pending zip =="
grep -n "strict=True" psh/interactive/history_manager.py

echo "== C5: resolve_command call sites in psh/executor/ =="
grep -rn "resolve_command(" psh/executor/ --include='*.py'

echo "== C6: iter_command_units definition + callers in psh/ =="
grep -rn "iter_command_units" psh/ --include='*.py'

echo "== C7: second-chunker sweep — other unit-splitting entry points in scripting =="
grep -rn "def .*command_unit\|def .*split.*unit\|def .*iter.*unit" psh/scripting/ --include='*.py'

echo "== C8: OpenDescription construction sites (lifecycle rule owners) =="
grep -rn "OpenDescription(" psh/ --include='*.py'
