"""FROZEN characterization table for ``find_command_substitution_end``.

This is a SAFETY NET for the decomposition refactor of the command-
substitution boundary scanner (psh/lexer/cmdsub_scanner.py). Every row
records the EXACT output the *pre-refactor* implementation produced for a
corpus input that exercises a distinct branch / construct of the scanner:
nested ``$(...)``, backticks, all four quote forms, escapes, ``${...}``,
arithmetic ``$((...))``, group/subshell parens, arithmetic commands
``((...))``, comments, heredocs (``<<``/``<<-``, quoted/unquoted/escaped
delimiters, here-strings, multi-heredoc, paren-in-body, unterminated),
``case``..``esac`` (patterns, ``(``-patterns, alternatives, ``;;``/``;&``/
``;;&``, nesting, extglob, malformed, keyword-at-command-position), other
command-position keywords, and adversarial nesting / edge cases.

Each row is ``(label, text, start_pos, expected_end, expected_found,
expected_pending_after)`` where ``expected_pending_after`` is the final
state of the mutated ``pending_heredocs`` list. The refactor MUST keep
every row passing byte-for-byte.

DO NOT regenerate these expected values from the current code if a row
ever fails — a failure means behavior changed. Generated by
tmp/gen_corpus.py against the pre-refactor implementation.
"""

import pytest

from psh.lexer.cmdsub_scanner import find_command_substitution_end

# (label, text, start_pos, expected_end, expected_found, expected_pending_after)
FROZEN_CASES = [
    ('simple', 'echo hello)', 0, 11, True, []),
    ('empty', ')', 0, 1, True, []),
    ('unterminated', 'echo hello', 0, 10, False, []),
    ('trailing_after_close', 'echo a) tail', 0, 7, True, []),
    ('nested_group_parens', 'echo (nested) word) tail', 0, 19, True, []),
    ('just_open_paren', '(', 0, 1, False, []),
    ('deeply_nested_groups', '((( ))) )', 0, 9, True, []),
    ('sq_paren', "echo ')' x)", 0, 11, True, []),
    ('sq_unterminated', "echo 'abc", 0, 9, False, []),
    ('sq_with_close_inside', "echo ')')", 0, 9, True, []),
    ('sq_empty', "echo ''))", 0, 8, True, []),
    ('dq_paren', 'echo ")" x)', 0, 11, True, []),
    ('dq_unterminated', 'echo "abc', 0, 9, False, []),
    ('dq_escaped_quote', 'echo "a\\"b")', 0, 12, True, []),
    ('dq_nested_cmdsub', 'echo "$(echo hi)")', 0, 18, True, []),
    ('dq_nested_cmdsub_unterminated', 'echo "$(echo hi"', 0, 16, False, []),
    ('dq_nested_arith', 'echo "$((1+2))")', 0, 16, True, []),
    ('dq_nested_arith_unterminated', 'echo "$((1+2"', 0, 13, False, []),
    ('dq_nested_brace', 'echo "${x}")', 0, 12, True, []),
    ('dq_nested_brace_unterminated', 'echo "${x")', 0, 11, False, []),
    ('dq_backtick', 'echo "`cmd`")', 0, 13, True, []),
    ('dq_backtick_unterminated', 'echo "`cmd")', 0, 12, False, []),
    ('esc_paren', 'echo \\) x)', 0, 10, True, []),
    ('esc_close_paren', 'echo \\))', 0, 8, True, []),
    ('trailing_backslash', 'echo \\', 0, 6, False, []),
    ('line_continuation', 'echo \\\nhi)', 0, 10, True, []),
    ('esc_dollar', 'echo \\$x)', 0, 9, True, []),
    ('backtick', 'echo `date`)', 0, 12, True, []),
    ('backtick_unterminated', 'echo `date)', 0, 11, False, []),
    ('backtick_escaped', 'echo `a\\`b`)', 0, 12, True, []),
    ('ansi_c', "echo $'a)b')", 0, 12, True, []),
    ('ansi_c_escaped_quote', "echo $'a\\'b')", 0, 13, True, []),
    ('ansi_c_unterminated', "echo $'abc)", 0, 11, False, []),
    ('locale_str', 'echo $"a)b")', 0, 12, True, []),
    ('locale_str_unterminated', 'echo $"abc)', 0, 11, False, []),
    ('arith_expansion', 'echo $((1+2)))', 0, 14, True, []),
    ('arith_expansion_unterminated', 'echo $((1+2)', 0, 12, False, []),
    ('nested_cmdsub', 'echo $(date))', 0, 13, True, []),
    ('nested_cmdsub_unterminated', 'echo $(date)', 0, 12, False, []),
    ('brace_expansion', 'echo ${x})', 0, 10, True, []),
    ('brace_expansion_op', 'echo ${x:-default})', 0, 19, True, []),
    ('brace_expansion_unterminated', 'echo ${x)', 0, 9, False, []),
    ('bare_dollar', 'echo $)', 0, 7, True, []),
    ('dollar_at_end', 'echo $', 0, 6, False, []),
    ('double_dollar_paren_nested', 'echo $($(date)))', 0, 16, True, []),
    ('comment_paren', 'echo hi # not-a-paren )', 0, 23, False, []),
    ('comment_then_close', 'echo hi # comment\n)', 0, 19, True, []),
    ('comment_no_newline_unterminated', 'echo hi #comment', 0, 16, False, []),
    ('hash_not_word_start', 'echo a#b)', 0, 9, True, []),
    ('hash_word_start_after_space', 'echo a #b)\n)', 0, 12, True, []),
    ('subshell', '(echo hi))', 0, 10, True, []),
    ('arith_command', '((1+2)))', 0, 8, True, []),
    ('arith_command_no_close', '((1+2)', 0, 6, False, []),
    ('double_paren_not_arith', '( (echo hi) ))', 0, 14, True, []),
    ('semicolon', 'echo a; echo b)', 0, 15, True, []),
    ('pipe', 'echo a | grep b)', 0, 16, True, []),
    ('ampersand', 'echo a & echo b)', 0, 16, True, []),
    ('and_and', 'a && b)', 0, 7, True, []),
    ('or_or', 'a || b)', 0, 7, True, []),
    ('redirect_out', 'echo hi > file)', 0, 15, True, []),
    ('redirect_in', 'cat < file)', 0, 11, True, []),
    ('here_string', 'cat <<< word)', 0, 13, True, []),
    ('heredoc_same_line_close', 'cat <<EOF)', 0, 10, True, [['EOF', False]]),
    ('heredoc_body', 'cat <<EOF\nline1\nEOF\n)', 0, 21, True, []),
    ('heredoc_body_unterminated', 'cat <<EOF\nline1\n', 0, 16, False, [['EOF', False]]),
    ('heredoc_dash', 'cat <<-EOF\n\tline\n\tEOF\n)', 0, 23, True, []),
    ('heredoc_quoted_delim', "cat <<'EOF'\n$x\nEOF\n)", 0, 20, True, []),
    ('heredoc_dquoted_delim', 'cat <<"EOF"\nx\nEOF\n)', 0, 19, True, []),
    ('heredoc_escaped_delim', 'cat <<\\EOF\nx\nEOF\n)', 0, 18, True, []),
    ('heredoc_no_delim', 'cat <<\n)', 0, 8, True, []),
    ('heredoc_paren_in_body', 'cat <<EOF\n)\nEOF\n)', 0, 17, True, []),
    ('two_heredocs', 'cat <<A <<B\naaa\nA\nbbb\nB\n)', 0, 25, True, []),
    ('case_basic', 'case x in x) echo hi;; esac)', 0, 28, True, []),
    ('case_paren_pattern', 'case x in (x) echo hi;; esac)', 0, 29, True, []),
    ('case_multi_pattern', 'case x in a|b) echo hi;; esac)', 0, 30, True, []),
    ('case_fallthrough', 'case x in a) echo a;& b) echo b;; esac)', 0, 39, True, []),
    ('case_continue_match', 'case x in a) echo a;;& b) echo b;; esac)', 0, 40, True, []),
    ('case_unterminated_no_esac', 'case x in x) echo hi', 0, 20, False, []),
    ('case_bare_close_no_esac', 'case x in x) echo hi)', 0, 21, False, []),
    ('case_nested', 'case x in x) case y in y) echo z;; esac;; esac)', 0, 47, True, []),
    ('case_with_cmdsub_in_body', 'case x in x) echo $(date);; esac)', 0, 33, True, []),
    ('case_extglob_in_pattern', 'case x in @(a|b)) echo hi;; esac)', 0, 33, True, []),
    ('case_malformed_no_in', 'case x y) echo hi)', 0, 9, True, []),
    ('case_esac_immediately', 'case x in esac)', 0, 15, True, []),
    ('echo_case_not_keyword', 'echo case in x) tail)', 0, 15, True, []),
    ('case_comment_in_pattern_expect', 'case x in #c\n x) echo hi;; esac)', 0, 32, True, []),
    ('case_subject_cmdsub', 'case $(echo x) in x) echo hi;; esac)', 0, 36, True, []),
    ('case_empty_subject_unusual', 'case in in in) echo hi;; esac)', 0, 30, True, []),
    ('if_then', 'if true; then echo hi; fi)', 0, 26, True, []),
    ('for_loop', 'for i in a b; do echo $i; done)', 0, 31, True, []),
    ('while_loop', 'while true; do break; done)', 0, 27, True, []),
    ('brace_group', '{ echo hi; })', 0, 13, True, []),
    ('offset_start', 'XX echo hi)', 3, 11, True, []),
    ('offset_in_text', '$(echo hi)', 2, 10, True, []),
    ('paren_in_dq_in_cmdsub', 'echo "$(echo \\")\\")")', 0, 21, True, []),
    ('deeply_nested_cmdsub', '$($($(echo x))))', 0, 16, True, []),
    ('case_in_subshell', '(case x in x) echo;; esac))', 0, 27, True, []),
    ('mixed_quotes', 'echo \'a\'"b"$\'c\')', 0, 16, True, []),
    ('paren_after_word_no_space', 'foo(bar))', 0, 9, True, []),
    ('empty_after_open', '', 0, 0, False, []),
    ('only_whitespace', '   ', 0, 3, False, []),
    ('only_newline', '\n', 0, 1, False, []),
    ('tab_word', '\techo hi)', 0, 9, True, []),
]


@pytest.mark.parametrize(
    "label,text,start,expected_end,expected_found,expected_pending",
    FROZEN_CASES,
    ids=[c[0] for c in FROZEN_CASES],
)
def test_cmdsub_scanner_characterization(
    label, text, start, expected_end, expected_found, expected_pending
):
    from psh.utils.heredoc_detection import PendingHeredocQueue
    pending = PendingHeredocQueue()
    end, found = find_command_substitution_end(text, start, pending)
    assert (end, found) == (expected_end, expected_found)
    # Pending heredocs are HeredocSpec values (campaign S2); the frozen
    # table's [cooked_delimiter, strip_tabs] rows compare against the
    # spec's cooked/strip_tabs facts — same semantics as the pre-S2
    # (delimiter, strip_tabs) tuples.
    assert [[s.cooked, s.strip_tabs] for s in pending.specs] == expected_pending
