#!/bin/bash
# B16 — instrument MANIFEST, command-generated and SELF-EXCLUDING.
#
# Self-excluding: the manifest lists every committed instrument EXCEPT itself
# and its own output, because a manifest that lists its own md5 can never be
# regenerated to match (writing the file changes the file). 4B.1 lesson.
#
# Counts are DERIVED here, never hand-tallied — a "N transcripts" line written
# by hand is the exact drift 5C.1's frozen ledger hit.
set -uo pipefail
cd /Users/pwilson/src/psh-r5c-2
DIR=docs/reviews/evidence/boundary_remediation_2026-07/5c.2-rescue/instruments
SELF="B16_manifest.sh"
SELFOUT="MANIFEST.md5"

echo "# Slot 5C.2 — instrument manifest"
echo
echo "Command-generated by \`tmp/w5c2-instruments/$SELF\`; SELF-EXCLUDING (this"
echo "generator and \`$SELFOUT\` are deliberately absent — a manifest cannot"
echo "contain its own hash). Regenerate and diff to verify nothing drifted."
echo
echo "Tree: \`$DIR\`"
echo "Tip: \`$(git rev-parse HEAD)\`"
echo
echo "| md5 | bytes | file |"
echo "|---|---|---|"
n=0
for f in $(cd "$DIR" && ls | sort); do
    [ "$f" = "$SELF" ] && continue
    [ "$f" = "$SELFOUT" ] && continue
    md5=$(md5 -q "$DIR/$f")
    size=$(wc -c < "$DIR/$f" | tr -d ' ')
    echo "| \`$md5\` | $size | \`$f\` |"
    n=$((n + 1))
done
echo
echo "**Files listed: $n** (derived by the loop above, not hand-counted.)"
