#!/bin/bash
# Slot 5B.1 instrument 20 — D10 SIGN-OFF: committed rescue tree vs my originals.
#
# Verifies BOTH DIRECTIONS (R6):
#   (1) every committed file is byte-identical to my worktree original
#   (2) nothing of mine is MISSING from the commit
#   (3) nothing EXTRA is in the commit that did not come from me
#   (4) MANIFEST.md5 recomputed against the committed bytes
#
# Comparison is by md5 of BYTES read from the commit (`git show`) vs bytes on
# disk — never by size, date, or diff-looks-empty.
#
# ONE expected difference, declared by R6 in advance: the committed
# INTEGRATOR-INBOX.md copy runs through R5; R6/R7 land in the post-merge
# addendum. That is checked as a PREFIX relationship, not waved through.
set -u
ROOT="${1:-$(git rev-parse --show-toplevel)}"
SHA="${2:-a8c5de8f}"
cd "$ROOT" || exit 2

RESCUE="docs/reviews/evidence/boundary_remediation_2026-07/5b.1-rescue"

echo "instrument 20 — sign-off byte verification"
echo "ROOT=$ROOT"
echo "verifying commit: $SHA  ($(git log -1 --format=%s "$SHA"))"
echo "my worktree HEAD: $(git rev-parse --short HEAD)"
echo

# --- map committed path -> my original path -------------------------------
mine_for() {
  case "$1" in
    "$RESCUE/brief.md")             echo "tmp/brief-5b1.md" ;;
    "$RESCUE/ledger.md")            echo "tmp/w5b1-ledger.md" ;;
    "$RESCUE/INTEGRATOR-INBOX.md")  echo "INTEGRATOR-INBOX.md" ;;
    "$RESCUE/MANIFEST.md5")         echo "" ;;   # generated by integrator
    "$RESCUE/instruments/"*)        echo "tmp/w5b1-instruments/${1#"$RESCUE/instruments/"}" ;;
    "$RESCUE/transcripts/"*)        echo "tmp/w5b1-transcripts/${1#"$RESCUE/transcripts/"}" ;;
    *)                              echo "?" ;;
  esac
}

committed=$(git ls-tree -r --name-only "$SHA" -- "$RESCUE/" | sort)
n_committed=$(echo "$committed" | grep -c . )

echo "=== (1) COMMITTED FILES: $n_committed — byte-compare each to my original ==="
identical=0; differing=0; unmapped=0; generated=0
DIFFLIST=""
while IFS= read -r c; do
  [ -z "$c" ] && continue
  m=$(mine_for "$c")
  if [ "$m" = "?" ]; then
    echo "  UNMAPPED       $c"
    unmapped=$((unmapped+1)); continue
  fi
  if [ -z "$m" ]; then
    echo "  GENERATED      $(basename "$c")  (integrator-produced; verified in section 4)"
    generated=$((generated+1)); continue
  fi
  chash=$(git show "$SHA:$c" | md5 -q)
  if [ ! -f "$ROOT/$m" ]; then
    echo "  MY COPY GONE   $c   (expected at $m)"
    differing=$((differing+1)); DIFFLIST="$DIFFLIST $c"; continue
  fi
  mhash=$(md5 -q "$ROOT/$m")
  if [ "$chash" = "$mhash" ]; then
    identical=$((identical+1))
  else
    echo "  *** DIFFERS    $c"
    echo "        committed md5 $chash"
    echo "        mine      md5 $mhash   ($m)"
    differing=$((differing+1)); DIFFLIST="$DIFFLIST $c"
  fi
done <<EOF
$committed
EOF
echo
echo "  byte-identical: $identical    differing: $differing    "\
"generated: $generated    unmapped: $unmapped"
echo

echo "=== (2) COMPLETENESS: is anything of MINE missing from the commit? ==="
# SELF-EXCLUDING: this instrument and its transcript were created AFTER the
# ceremony commit, to perform this very check. A commit cannot contain the
# artifact that verifies it, so counting them as "missing" is an artifact of
# the checker, not a defect in the tree (same principle as the manifest's own
# self-exclusion).
SELF="20_signoff_byte_verify"
missing=0
for f in tmp/w5b1-instruments/*; do
  b=$(basename "$f")
  case "$b" in *"$SELF"*) echo "  (self-excluded: instruments/$b)"; continue;; esac
  echo "$committed" | grep -qx "$RESCUE/instruments/$b" || {
    echo "  MISSING FROM COMMIT: instruments/$b"; missing=$((missing+1)); }
done
for f in tmp/w5b1-transcripts/*; do
  b=$(basename "$f")
  case "$b" in *"$SELF"*) echo "  (self-excluded: transcripts/$b)"; continue;; esac
  echo "$committed" | grep -qx "$RESCUE/transcripts/$b" || {
    echo "  MISSING FROM COMMIT: transcripts/$b"; missing=$((missing+1)); }
done
for pair in "tmp/brief-5b1.md:brief.md" "tmp/w5b1-ledger.md:ledger.md" \
            "INTEGRATOR-INBOX.md:INTEGRATOR-INBOX.md"; do
  src=${pair%%:*}; dst=${pair##*:}
  echo "$committed" | grep -qx "$RESCUE/$dst" || {
    echo "  MISSING FROM COMMIT: $dst (from $src)"; missing=$((missing+1)); }
done
echo "  missing: $missing"
echo

echo "=== (3) EXTRAS: anything committed that did not come from me? ==="
extras=0
while IFS= read -r c; do
  [ -z "$c" ] && continue
  m=$(mine_for "$c")
  if [ "$m" = "?" ]; then
    echo "  EXTRA (unmapped): $c"; extras=$((extras+1))
  elif [ -n "$m" ] && [ ! -f "$ROOT/$m" ]; then
    echo "  EXTRA (no origin): $c"; extras=$((extras+1))
  fi
done <<EOF
$committed
EOF
echo "  extras: $extras   (MANIFEST.md5 is integrator-generated, not an extra)"
echo

echo "=== (4) MANIFEST.md5 RECOMPUTED against committed bytes ==="
tmpdir=$(mktemp -d "${TMPDIR:-/tmp}/w5b1-signoff.XXXXXX")
git show "$SHA:$RESCUE/MANIFEST.md5" > "$tmpdir/MANIFEST.md5" 2>/dev/null
entries=$(grep -c . "$tmpdir/MANIFEST.md5" 2>/dev/null || echo 0)
echo "  manifest entries: $entries"
echo "  --- verifying each entry against the committed blob ---"
mok=0; mbad=0; mskip=0
while IFS= read -r line; do
  [ -z "$line" ] && continue
  h=$(echo "$line" | awk '{print $1}')
  p=$(echo "$line" | sed 's/^[0-9a-f]*[[:space:]]*//')
  case "$h" in [0-9a-f][0-9a-f]*) ;; *) mskip=$((mskip+1)); continue;; esac
  # The manifest records paths relative to the rescue dir as `./name`; git
  # will not resolve `<dir>/./name`, so normalise the leading `./` first.
  # (First pass reported all 41 entries "unresolved" for exactly this reason —
  # a checker bug that would have read as a clean manifest had I only counted
  # mismatches.)
  p="${p#./}"
  cand="$RESCUE/$p"
  if git cat-file -e "$SHA:$cand" 2>/dev/null; then
    actual=$(git show "$SHA:$cand" | md5 -q)
  elif git cat-file -e "$SHA:$p" 2>/dev/null; then
    actual=$(git show "$SHA:$p" | md5 -q)
  else
    echo "    UNRESOLVED entry: $p"; mskip=$((mskip+1)); continue
  fi
  if [ "$h" = "$actual" ]; then mok=$((mok+1)); else
    echo "    *** MANIFEST MISMATCH: $p"
    echo "          manifest $h"
    echo "          actual   $actual"
    mbad=$((mbad+1))
  fi
done < "$tmpdir/MANIFEST.md5"
echo "  manifest verified: $mok    mismatched: $mbad    unresolved/skipped: $mskip"
echo "  manifest self-excluding? $(grep -c 'MANIFEST.md5' "$tmpdir/MANIFEST.md5") occurrence(s) of its own name (0 = self-excluding)"
echo

echo "=== (5) THE ONE DECLARED DIFFERENCE: inbox copy runs through R5 ==="
git show "$SHA:$RESCUE/INTEGRATOR-INBOX.md" > "$tmpdir/inbox_committed.md" 2>/dev/null
cl=$(wc -l < "$tmpdir/inbox_committed.md" | tr -d ' ')
ml=$(wc -l < "$ROOT/INTEGRATOR-INBOX.md" | tr -d ' ')
echo "  committed copy: $cl lines; mine now: $ml lines"
echo "  entries in committed copy:"
grep -n "^## R\|^## D" "$tmpdir/inbox_committed.md" | tail -4 | sed 's/^/    /'
echo "  PREFIX CHECK (committed copy must be an exact prefix of mine, not a variant):"
prefix_ok=0
if head -n "$cl" "$ROOT/INTEGRATOR-INBOX.md" | cmp -s - "$tmpdir/inbox_committed.md"; then
  echo "    EXACT PREFIX — every committed byte matches mine; the only delta is"
  echo "    the entries appended after R5, exactly as R6 declared."
  prefix_ok=1
else
  echo "    *** NOT A PREFIX — the committed copy diverges, not merely truncates."
fi
rm -rf "$tmpdir"
echo

# The inbox is the ONE difference R6 declared in advance. It counts as expected
# ONLY if the prefix check proves it is a pure truncation at R5 — a divergent
# copy would still be a real mismatch. Discount it here, never wave it through.
expected_diff=0
case "$DIFFLIST" in
  *INTEGRATOR-INBOX.md*) [ "$prefix_ok" -eq 1 ] && expected_diff=1 ;;
esac
real_differing=$((differing - expected_diff))

echo "=== VERDICT ==="
echo "  differing=$differing  of which R6-declared-and-prefix-proven=$expected_diff"
echo "  -> real mismatches=$real_differing  missing=$missing  extras=$extras"\
" manifest_bad=$mbad  manifest_unresolved=$mskip"
if [ "$real_differing" -eq 0 ] && [ "$missing" -eq 0 ] && [ "$extras" -eq 0 ] \
   && [ "$mbad" -eq 0 ] && [ "$mskip" -eq 0 ]; then
  echo "  PASS — committed rescue tree is byte-exact with my originals, complete"
  echo "  in both directions, and its manifest recomputes entry-by-entry."
else
  echo "  FAIL — see counts above"
  echo "  offenders:$DIFFLIST"
fi
echo
echo "instrument 20 done"
